### ISSUE TITLE
Snapshots?

### ISSUE THREAD

**Issue by heitorPB** [base-org/node#103]
Hello,

I'm bootstraping a new mainnet node and it seems it will take several days to sync. Are there any snapshots that I can use to speed up this process?

**Comment by wbnns** [comment]
@heitorPB 

Hey there! Yes, it's now possible to always get the latest available snapshot of the Base chain on mainnet and/or testnet by using the following CLI commands. The snapshots are updated every hour.

**Mainnet**
```
wget https://base-mainnet-archive-snapshots.s3.us-east-1.amazonaws.com/$(curl https://base-mainnet-archive-snapshots.s3.us-east-1.amazonaws.com/latest)
```

**Testnet**
```
wget https://base-goerli-archive-snapshots.s3.us-east-1.amazonaws.com/$(curl https://base-goerli-archive-snapshots.s3.us-east-1.amazonaws.com/latest)
```

**Comment by alik-agaev** [comment]
Hello! 
@wbnns  Do you know about sepolia snapshot that we, node operators, can use? There is an [file in S3](https://base-sepolia-archive-snapshots.s3.us-east-1.amazonaws.com/latest), but it is not stated in Readme.
