### ISSUE TITLE
prune ancient data

### ISSUE THREAD

**Issue by zxsimba** [base-org/node#107]
Is there a way to prune ancient data to limit disk space usage?
Is there a way to prune ancient data in real time like bnb chain:
https://docs.bnbchain.org/docs/validator/node-maintenance#prune-ancient-data-in-real-time

**Comment by HiroyukiNaito** [comment]
With discussed in the discord, I made PR the operation.

**Comment by wbnns** [comment]
Hello! This would be a great option to have available but unfortunately it isn't supported on the OP Stack at this time.
