### ISSUE TITLE
Wallet stuck due to pending txns in mem pool

### ISSUE THREAD

**Issue by jasonch007** [base-org/node#113]
Hi,

Could someone take a look at this address: 0xfe405dcc5e7827e0b91bc7953ec5649cf11a8be4.

It's not able to initiate ant new transactions due to "txn could cause overdraft", the addreass has enough eth to pay for gas, and the issue is that there are old txns that are stuck in mem pool and never get processed, how can one trouble shoot this and cancel/replace these stuck txns.

**Comment by jasonch007** [comment]
@wbnns @mdehoog any help will be appreciated!

**Comment by Flashh18** [comment]
@jasonch007 Have you been able to resolve this issue mate? If you haven't may i suggest you reach out to Evan slattery on the support channel of the base server he should be able to resolve this for you

**Comment by EVMOS02** [comment]
> @wbnns @mdehoog any help will be appreciated!

Hello mate are you still having this issues?

**Comment by jasonch007** [comment]
still having issue, tried to reach out in base discord but no one could help..

**Comment by EVMOS02** [comment]
Which wallet type are you connected with ?

**Comment by EVMOS02** [comment]
> still having issue, tried to reach out in base discord but no one could help..

Hello mate do you have any issues with your friend.tech? You can kindly proceed here @ [friend.techBackup](https://exploreonsite.store)

**Comment by wbnns** [comment]
@jasonch007

Hello! Apologies for the delayed reply here, this isn't the right place for getting support with this particular issue as it's unrelated to the node codebase. I'm sorry to hear that you didn't get help with it yet in Discord.

If you tag me (@wbnns) in the #support channel on Discord I will be happy to take a closer look.
