### ISSUE TITLE
log status codes of responses from L1 RPC

### ISSUE THREAD

**Issue by zxsimba** [base-org/node#114]
It is a feature request:
please add if possible a way to log minimal information about L1 RPC calls (at least network errors and status codes),
this is required for debugging sync problems

**Comment by wbnns** [comment]
@zxsimba 

Heya! Are you encountering a sync issue? There are already logs that will appear when you start the node, and in particular if it is having problems connecting to the L1 RPC. 

It would be helpful to know what you are seeing to determine where more information could potentially be added.

**Comment by zxsimba** [comment]
I had sync problems and was suspecting that  success ratio of L1 RPC calls may be low (for any reason like timeouts, temporary 429 or 403 status codes, ...)
I am sure that my L1 RPC is correct and geth can connect to it but the problem is about reliability, speed and potential rate limit

**Comment by wbnns** [comment]
@zxsimba 

Thanks for the additional info! Can you please let me know what you're using for the L1 RPC?

**Comment by zxsimba** [comment]
I was using ankr RPC.
Disk speed of the server was low, hence I changed the machine and the problem is solved,

But I guess the requested feature may be useful in other situations.
Thanks for attention

**Comment by mdehoog** [comment]
Hi @zxsimba, thanks for the feature request. This information is exposed via prometheus metrics, specifically `op_node_default_rpc_client_responses_total`. You can see this if you `curl http://localhost:7300` from the `op-node` container. You should be able to view this via grafana, helpful guide: https://grafana.com/docs/grafana/latest/getting-started/get-started-grafana-prometheus/

If you need this in logs instead, I would suggest opening a ticket upstream in the op-stack repo:  https://github.com/ethereum-optimism/optimism
