### ISSUE TITLE
Add instructions for snapshots in README.md

### ISSUE THREAD

**Issue by d-szns** [base-org/node#118]
### Description
The current [README](https://github.com/base-org/node#snapshots) mentions snapshots to speed up syncing of nodes. However there are no clear instructions on how to use the snapshot upon startup of the node.

### Suggested Solution
Add a section on how to use the snapshots. There was a helpful thread on [Discord](https://discord.com/channels/1067165013397213286/1078812168679600239/1136565247025614858) that summarized the process. It would help new node operators to have a single source to reference when starting a node.

**Comment by wbnns** [comment]
@d-szns 

Thanks for the feedback! We'll look into adding this. :+1:

**Comment by MindlessSteel** [comment]
Yes publish the snapshot.
Set-up for those that don't use discord, not everyone uses that
Platform.
