### ISSUE TITLE
character error

### ISSUE THREAD

**Issue by HerculesNode** [base-org/node#124]
https://github.com/base-org/node/blob/v0.3.2/docker-compose.yml#L5

found in the docker-compose file

In line 5 and line 19, the ( . ) sign after the build : tag breaks the configuration.

**Comment by mdehoog** [comment]
the `.` means to build the local `Dockerfile`. Do you have the full repo checked out, and the latest docker / docker-compose installed? what error are you seeing?

**Comment by HerculesNode** [comment]
Dockerfile yeah sory.

https://github.com/base-org/node/blob/v0.3.2/op-node-entrypoint#L5

node-node-1  | ./op-node-entrypoint: 5: [: Illegal number:

**Comment by mdehoog** [comment]
Oh thank you for the report, this is a duplicate of #122, which was fixed in #123 and released in `v0.3.3`.
