### ISSUE TITLE
api: Requesting for adding new rpc command eth_getBlockReceipts

### ISSUE THREAD

**Issue by chetankashetti** [base-org/node#125]
Currently, the way we obtain complete information about all transactions in a block is as follows:

Call eth_getBlockBy{Number,Hash} to retrieve all transaction data for a block;
Iterate through all the transaction data obtained above and call eth_getTransactionReceipt to retrieve the receipt data for each transaction.
This method is highly inefficient for obtaining large amounts of block and transaction data. an RPC that returns all the receipt data for a block in one call, will be very helpful for devs.

**Comment by wbnns** [comment]
@chetankashetti 

Hi there! Thanks for reaching out and opening this issue. 

To confirm, you would like a method that provides all the receipt data for a provided block? Could you please share more details about the specific change you're proposing be made so we can review in more detail?

**Comment by roberto-bayardo** [comment]
Unlikely we'd add this as it would be a very expensive call leading to a DoS vector.  You could consider batch requests: https://www.quicknode.com/guides/ethereum-development/transactions/how-to-make-batch-requests-on-ethereum

**Comment by mdehoog** [comment]
Thanks for the request. There was an implementation of this in geth that was closed: https://github.com/ethereum/go-ethereum/pull/19721. Might suggest asking a question there.
