### ISSUE TITLE
Enable snap sync

### ISSUE THREAD

**Issue by kaliubuntu0206** [base-org/node#132]
https://github.com/ethereum-optimism/optimism/pull/6243#issuecomment-1784396213

Base nodes would be able to sync much quicker with snap sync but seems like it is disabled by default https://github.com/base-org/node/blob/main/geth-entrypoint#L62.

Also, it should have bootnodes for op-geth to connect each other.

**Comment by roberto-bayardo** [comment]
Snap sync has yet to be sufficiently tested for op chains which is why it's disabled for now. Would be good to get it tested and activated however.

**Comment by kaliubuntu0206** [comment]
@roberto-bayardo Could you enable `--state.scheme=path` option for op-geth? It will reduce disk usage by more than 50% with my benchmarks

**Comment by roberto-bayardo** [comment]
looking forward to enabling path-based state db as well when it's more battle tested. geth team recommends leaving it disabled for lower risk profile for the time being.

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 Are there any updates about full mode snapshot or snap sync?

**Comment by ohnodev** [comment]
It's been almost 2 years and still no snap mode. Base really expects us to have 10TB+ of storage to manage everything.... insane... Base keeps talking about that it's for everyone, but yeah you can only afford to run a base node if you can pay $1k+ a month for a cloud provider. For those of us who are tired of paying overpriced RPC endpoints like Alchemy a snap sync full implementation would really go along with Base's "base is for everyone" propaganda.
