### ISSUE TITLE
Support op-erigon scripts and docker images

### ISSUE THREAD

**Issue by kaliubuntu0206** [base-org/node#137]
https://github.com/testinprod-io/op-erigon

Useful for running an archive nodes

**Comment by HiroyukiNaito** [comment]
In my recognition, op-geth store all state from the beginning.
So it's near to archive node. Right?

**Comment by kaliubuntu0206** [comment]
@HiroyukiNaito No, geth and op-geth is non-archive pruned node by default ( by recent 128 blocks ).

But seems like the docker configuration would run op-geth node in archive state which would be 10x heavier than the pruned nodes https://github.com/base-org/node/blob/main/geth-entrypoint#L65.

op-erigon is much lighter, more performant for archive node purposes.

**Comment by roberto-bayardo** [comment]
> @HiroyukiNaito No, geth and op-geth is non-archive pruned node by default ( by recent 128 blocks ).
> 
> But seems like the docker configuration would run op-geth node in archive state which would be 10x heavier than the pruned nodes https://github.com/base-org/node/blob/main/geth-entrypoint#L65.
> 
> op-erigon is much lighter, more performant for archive node purposes.

This is correct. Also note that op-reth is now an option as well, which is even more lightweight than op-erigon.

**Comment by HiroyukiNaito** [comment]
So, the current base node run with `--gcmode=archive `  and it stores all state from the beginning with current Docker setting.
Thus, the operational base node (op-geth) stores all state from the beginning.
Can `--gcmode=full`  reduce the disk space now, this operationa base op-geth?

**Comment by kaliubuntu0206** [comment]
@HiroyukiNaito I am running and could run op-geth nodes without `--gcmode=archive` flag. The flag is only useful if you need to access historical states that should be simulated with old blocks. ( For example looking up on a previously recorded contract data that has been overwritten ).

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 Thanks! Does it sync quickly from the past 128 blocks? Honestly now it sync from 300,000 block from the latest snapshot.

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 I removed the option but it is syncing from the very past block. So, I don't think it has any changes from the option `--gcmode=archive`.

**Comment by kaliubuntu0206** [comment]
@HiroyukiNaito The option doesn't change syncing speed but it will reduce your disk footprint

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 Thanks, but my node hangs from the setting, so backed again to previous setting.

**Comment by kaliubuntu0206** [comment]
@HiroyukiNaito Changing pruning settings will require you to remove existing DB and resync

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 So, it needs to download snapshot again. Oh, It's hell.

**Comment by kaliubuntu0206** [comment]
cc @roberto-bayardo I think providing snapshot for `--gcmode=full --state.scheme=path` would be also possible which would provide much lighter node

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 I tried to `--state.schme=path` on my node, but it emits error which suggest don't support. How to enable `--state.scheme=path`?

**Comment by kaliubuntu0206** [comment]
@roberto-bayardo Which op-geth version are you using? For the latest version and the version tagged for base I think it is supported?

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206  I use the latest https://github.com/base-org/node/blob/main/Dockerfile#L22 .
However, it emits with error.

**Comment by HiroyukiNaito** [comment]
```
node-geth-1  | Fatal: Failed to register the Ethereum service: incompatible state scheme, stored: hash, provided: path
node-geth-1  | Fatal: Failed to register the Ethereum service: incompatible state scheme, stored: hash, provided: path
```

**Comment by kaliubuntu0206** [comment]
@roberto-bayardo Could you remove the init command?

https://github.com/base-org/node/blob/main/geth-entrypoint#L22

It is unnecessary since op-geth and op-node baked in base mainnet and testnets with my knowledge

**Comment by kaliubuntu0206** [comment]
@HiroyukiNaito It is due to the init command, you should also add `--state.schme=path` flag on to the init command but I guess base chains would work without the init command since they are already supported.

**Comment by HiroyukiNaito** [comment]
@kaliubuntu0206 Thanks! In the mean time, I try to `--gcmode=full` and `--state.schem=path` from the start without a snapshot .
