### ISSUE TITLE
Is `eth_newPendingTransactionFilter` method disabled in Base node?

### ISSUE THREAD

**Issue by dreygur** [base-org/node#138]
Is `eth_newPendingTransactionFilter` method disabled in Base node?
Or can I enable it on my own node?

**Comment by danyalprout** [comment]
Hi @dreygur, `eth_newPendingTransactionFilter` is disabled by default in op-geth. This is to prevent any transaction leakage/MEV opportunities. There is more context on this [here](https://github.com/ethereum-optimism/op-geth/pull/118) and [here](https://status.base.org/incidents/m9fnx4p3bhp5).

You can enable it on your own node, but you'll only see transactions in that nodes mempool.
