### ISSUE TITLE
Providing `--gcmode=full` snapshot, is it possible technically?

### ISSUE THREAD

**Issue by HiroyukiNaito** [base-org/node#140]
Currently, Base seems to provide `--gcmode=archive` snapshot.
It needs significant time and space on a personal server for downloading.
In addition, catching up latest block from the snapshot is also daunting.
Is it possible to provide  `--gcmode=full` snapshot and run op-geth technically?

**Comment by mdehoog** [comment]
Yes this is possible technically. See [#126](https://github.com/base-org/node/issues/126#issuecomment-1799266583) for more info. Will keep that issue up-to-date if and when we have full snapshots available.
