### ISSUE TITLE
op-node-entrypoint is broken

### ISSUE THREAD

**Issue by feld** [base-org/node#143]
This was broken in  #119 

First, the shell script syntax is broken.

> "${OP_NODE_L2_ENGINE_RPC//ws/http}"

this obviously should be

> "${OP_NODE_L2_ENGINE_RPC}/ws/http"

Secondly, this won't work anyway because this endpoint returns a 404.

This change was not tested. Your v0.5.0 release has been out for a month.

Nobody noticed this for a month which is **_DEEPLY_** concerning. Is anyone actually running this chain?

**Comment by danyalprout** [comment]
Thanks for reporting @feld. Tried to repro your issue locally and it seems ok for me in bash. e.g.

```
bash-3.2$ TEST=http://geth:8551
bash-3.2$ echo ${TEST//http/ws}
ws://geth:8551
```

However the proposed change seems to not work as expected.
```
bash-3.2$ TEST=http://geth:8551
bash-3.2$ echo "${TEST}/http/ws"
http://geth:8551/http/ws
```

Are you by any change overriding OP_NODE_L2_ENGINE_RPC and does it have a second http in the URL? I wonder if we should switch the `//` to `/` to only replace the first occurrence 
```
bash-3.2$ TEST=http://gethhttp:8551
bash-3.2$ echo ${TEST//http/ws}
ws://gethws:8551
bash-3.2$ echo ${TEST/http/ws}
ws://gethhttp:8551
```

**Comment by feld** [comment]
the bash errors I received were related to my **OP_NODE_L2_ENGINE_RPC** still being **http://geth:8551** in my deployment instead of ws://

There is no mention of this breaking change in the release notes published with the v0.5.0 tag: https://github.com/base-org/node/releases/tag/v0.5.0

**Comment by mdehoog** [comment]
Hmmm were there any other changes? That should still not have been a breaking change?
```bash
> OP_NODE_L2_ENGINE_RPC=http://geth:8551
> echo ${OP_NODE_L2_ENGINE_RPC//ws/http}
http://geth:8551
```

**Comment by feld** [comment]
The real breaking change was that this requires *bash* for the entrypoint script now instead of sh, so those who cannot use your docker-compose due to our deployment strategies were caught off guard by 4d87a51d98844e912038d365f82fcaa5b81e79a1
