### ISSUE TITLE
The latest snapshot is very old

### ISSUE THREAD

**Issue by 0xZerohero** [base-org/node#149]
The documentation states that  _**the snapshots are updated every hour**_, but actually the latest snapshot is from the last month - 2023-10-29T17:54:12.000Z

**Comment by mdehoog** [comment]
Thanks @0xZerohero, acknowledged that these snapshots are behind, apologies for this. We are currently in the process of implementing a more reliable solution internally, hopefully have a new snapshot uploaded early next week.

**Comment by monu03** [comment]
Thank you

**Comment by Denis-score** [comment]
@mdehoog , any news about the new snapshot ?

**Comment by danyalprout** [comment]
@Denis-score we're just waiting for our mainnet/goerli snapshot jobs to run. If all goes well -- they should be complete this evening and I'll update the docs/post the updated links here. Thanks for your patience 🙏

**Comment by Shankusu993** [comment]
@danyalprout was it successful ? is the snapshot updated now? (assuming the link for new snapshot is same?)

I'd also like to learn about your snapshot job that you mentioned here. What does this job look like or the snapshot pipeline look like?  Asking so that If I or anyone wanted to have their own snapshots on a future date, this could be helpful.

Thanks in Advance

**Comment by danyalprout** [comment]
You should be able to fetch the snapshots from:

```
# Mainnet
wget https://base-snapshots-mainnet-archive.s3.amazonaws.com/$(curl https://base-snapshots-mainnet-archive.s3.amazonaws.com/latest)

# Sepolia
wget https://base-snapshots-sepolia-archive.s3.amazonaws.com/$(curl https://base-snapshots-sepolia-archive.s3.amazonaws.com/latest)

# Goerli
wget https://base-snapshots-goerli-archive.s3.amazonaws.com/$(curl https://base-snapshots-goerli-archive.s3.amazonaws.com/latest)
```

Please note, we're in the process of adding CNAMEs to these (so if we move S3 buckets ya'll wont be impacted).

@Shankusu993 our snapshot job, runs in k8s and uses some internal Coinbase infra to grab a snapshot from a node / zip it and upload it to S3.

**Comment by 0xZerohero** [comment]
@danyalprout It looks like the pipeline is not running regularly... the latest snapshot is already 5 days old.
Did you only run it once ?

**Comment by danyalprout** [comment]
Docs have been updated w/ the new URLs + frequency above:
https://docs.base.org/guides/run-a-base-node/#snapshots
