### ISSUE TITLE
Node refuse to start with erigon L1

### ISSUE THREAD

**Issue by Denis-score** [base-org/node#154]
Hello,

Ny node refuse to start when I use an erigon L1 node, with error : 
```
t=2023-11-24T13:43:31+0000 lvl=eror msg="Error initializing the rollup node" err="Post \"http://xxxx:8545/\": context deadline exceeded"
t=2023-11-24T13:43:31+0000 lvl=eror msg="Unable to create the rollup node"   error="Post \"http://xxxx:8545/\": context deadline exceeded"
t=2023-11-24T13:43:31+0000 lvl=crit msg="Application failed"                 message="Post \"http://xxxx:8545/\": context deadline exceeded"
```

All was working properly, and since I upgraded base to the last version, it refuse to start. Any idea ?

Thanks

**Comment by wbnns** [comment]
@Denis-score 

Hello, can you please share more details about the L1 node? Are you running it locally or are you using a third-party provider?

**Comment by Denis-score** [comment]
@wbnns locally. It's my own node running an `erigon version 2.53.4-c4843268`

**Comment by iMaxrs** [comment]
why you choose this node? do you have expirience with another and what was your profit?

**Comment by wbnns** [comment]
@Denis-score 

It looks like your Base node isn't able to connect to the local Erigon node that you're running. I see the `xxxx` in your log -- is this an external IP or are you omitting the localhost IP? Can you confirm it is reachable?

@iMaxrs 

Base Nodes are designed for developers and teams building on top of the network, or enthusiasts experimenting with interacting with the chain. There are no incentives or rewards for running a Base Node (hope that helps clarify!).

**Comment by wbnns** [comment]
@Denis-score 

Since it's been a while and we haven't heard back, I'm going to go ahead and close this issue. If you're still having a problem, though, just let us know and I'll reopen!
