### ISSUE TITLE
Ignoring already known beacon payload

### ISSUE THREAD

**Issue by fr4nc32c0** [base-org/node#159]
very often, i get the title message (WARN) on the op-geth container that slow the import of new blocks. For example:

INFO [12-10|18:40:11.211] Imported new potential chain segment     number=7,722,123 hash=06c1c8..a90c73 blocks=1 txs=5   mgas=7.718  elapsed=18.016s       mgasps=0.428    snapdiffs=1.14MiB    triedirty=0.00B
WARN [12-10|18:40:11.213] Ignoring already known beacon payload    number=7,722,123 hash=06c1c8..a90c73 age=18s
WARN [12-10|18:40:11.214] Ignoring already known beacon payload    number=7,722,123 hash=06c1c8..a90c73 age=18s
INFO [12-10|18:40:11.218] Chain head was updated                   number=7,722,123 hash=06c1c8..a90c73 root=c91ac8..57578a elapsed=2.545709ms

Do you know what that does mean and if i can avoid the delay?

Thank you 
Francesco

**Comment by wbnns** [comment]
@fr4nc32c0 

Heya! Are you currently able to sync to the tip? Or is this causing you to be unable to complete the sync? Also, to confirm, are you running the [latest version](https://github.com/base-org/node/releases/tag/v0.5.1) of Base Node?

**Comment by wbnns** [comment]
Since it's been a while and we haven't heard back, I'm going to go ahead and close this issue. If you're still having a problem, though, just let us know and I'll reopen!
