### ISSUE TITLE
noob questions on running without docker-compose

### ISSUE THREAD

**Issue by jotto** [base-org/node#162]
**question 1:** Is the "snapshot" for base? or for geth?

https://docs.base.org/guides/run-a-base-node/ suggests to download a snapshot, which I first assumed was for the base node's data directory ("latest available snapshot of the Base chain"), but I see no examples of specifying a data directory for base anywhere in this repo, instead the README says:

> Map a local data directory for **op-geth** by adding a volume mapping to the docker-compose.yaml

> This is where your node data will be stored. This is for example where you would extract your [snapshot](https://github.com/base-org/node#snapshots) to.

so now it seems like the "snapshot" was/is for **op-geth**... but is "op-geth" a special geth for optimism? or base? or is it the ethereum l1?

**question 2:** what is simplest `docker run` command for connecting to my own eth l1? (I am running erigon and I see the notes for "OP_NODE_L1_TRUST_RPC")

under the README's "Running in single container" section, I see:

> docker run --env-file .env.goerli -e OP_NODE_L2_ENGINE_RPC=ws://localhost:8551 -e OP_NODE_RPC_PORT=7545 ghcr.io/base-org/node:latest

but what are OP_NODE_L2_ENGINE_RPC and OP_NODE_RPC_PORT pointing to? The eth l1 node? or the base node? If it's the base node, why do the env files default to `OP_NODE_L2_ENGINE_RPC=ws://geth:8551`... suggesting it's for geth (which I assume is eth l1?)

**question 3:** I might be confused on actual components involved... is it simply 2 things: eth l1 archive node and base node? or is there a 3rd "geth-op" node?

**question 4:** is it possible to use a fork of erigon instead of this repo for running base?

* https://github.com/testinprod-io/op-erigon (actual fork)
* https://twitter.com/testinprod_io/status/1701255883655901390 (testinprod-io team suggesting it works)

**Comment by jotto** [comment]
My best guess is 3 separate things:

1. a fork of geth, for optimism, configured for base (handled by docker-compose)
2. base node (this repo) (handled by docker-compose) 
3. ethereum l1 node (handled separately)

in which case, to handle "Running in single container", you'd point the `OP_NODE_L2_ENGINE_RPC` and `OP_NODE_RPC_PORT` at the "op-geth" instance

![image](https://github.com/base-org/node/assets/16573/2bd2e937-b9a3-40ff-b454-900d9cd87a86)

image from: https://docs.optimism.io/builders/node-operators/overview

**Comment by wbnns** [comment]
@jotto 

Hi there!

> question 1: Is the "snapshot" for base? or for geth?

Yep! The snapshot is for Base.

> question 2: what is simplest docker run command for connecting to my own eth l1? (I am running erigon and I see the notes for "OP_NODE_L1_TRUST_RPC")

As you mentioned, that's correct, there are instructions in the README for running in a single container. That said, your L1 reference is actually what will go in the `.env` (e.g. `.env.goerli`). Using `.env.goerli` as an example, it's on Line 8. https://github.com/base-org/node/blob/main/.env.goerli#L8

> question 3: I might be confused on actual components involved... is it simply 2 things: eth l1 archive node and base node? or is there a 3rd "geth-op" node?

It is an L1 (Ethereum) and L2 (Base). Base runs on the OP Stack which is where  OP-Geth comes in. https://op-geth.optimism.io/

> question 4: is it possible to use a fork of erigon instead of this repo for running base?

I haven't seen this done, and haven't tried myself. But if you give it a go please let us know how it goes! 

* * *

I'm going to close this issue but if you have any other questions please don't hesitate to reply and let us know! Happy to try to help! 🤝 👍
