### ISSUE TITLE
Docker volume mount removed

### ISSUE THREAD

**Issue by Theo-** [base-org/node#164]
In https://github.com/base-org/node/pull/59, the volume mount for op-geth got removed. This caused our nodes to restart from zero after pulling the latest. 

Flagging in case it wasn't intentional, if it was, please close :)

**Comment by Bablu9693** [comment]
Very interesting project

**Comment by wbnns** [comment]
@Theo- 

Heya, happy new year! Thanks for reporting this! Let me look into this and will report back. 👍

**Comment by mdehoog** [comment]
hey @Theo-, this was intentional, but open to adding it back in. It was introduced in #49 but removed 5 days later because It is mentioned in the README as an option, but we didn't necessarily want to be opinionated about where the volume should be stored locally.

**Comment by danyalprout** [comment]
I think mounting a data dir by default seems reasonable, as anyone who restores from a snapshot needs that behavior. 

In the PR above, added a volume with a default name, that can be overriden by an env var.
