### ISSUE TITLE
Base node geth fails on file descriptor issue

### ISSUE THREAD

**Issue by TurtleSnail** [base-org/node#174]
Latest version of geth fails to run -- see below in Docker log
```
base-node-geth-1  | Fatal: Failed to raise file descriptor allowance: operation not permitted
base-node-geth-1  | Fatal: Failed to raise file descriptor allowance: operation not permitted
base-node-geth-1 exited with code 1
```

**Comment by wbnns** [comment]
@TurtleSnail 

Hi there! Hm, are you by chance setting up and running the node outside of the container?

**Comment by B1Q** [comment]
> @TurtleSnail
> 
> Hi there! Hm, are you by chance setting up and running the node outside of the container?

I have the same issue, I followed the installation guide and still get 

Fatal: Failed to raise file descriptor allowance: operation not permitted

I am just running the following command 
docker compose up --build
