### ISSUE TITLE
Syncing stuck after block #9101526 

### ISSUE THREAD

**Issue by tapas-jana** [base-org/node#180]
Hi..
I have been running a base node using docker-compose for last 5 months approx but recently it's syncing has been  stuck at #9101526 ("number": "0x8ae0d6"). geth docker container has the error below 
Served engine_forkchoiceUpdatedV1        conn=172.19.0.3:41636 reqid=2794 duration="131.543µs" err="Invalid parameters" errdata="{Error:forkChoiceUpdateV1 called post-shanghai}" 
can you help me ?

**Comment by mdehoog** [comment]
What version are you running?

**Comment by blocknodehub** [comment]
> What version are you running?

I have the same problem.The following two versions, respectively, can not continue to synchronize data, stop at 9101526 (0x8ae0d6)
 us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101304.2
us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101305.1-hotfix

**Comment by tapas-jana** [comment]
The problem has been solved, I downloaded the latest release and it's syncing again. Just for information there was an error with docker buildkit, I bypassed docker buildkit (DOCKER_BUILDKIT=0 docker-compose up --build -d) and it worked.
Thank you all

**Comment by tapas-jana** [comment]
thanks!!
