### ISSUE TITLE
node-node-1  | waiting for geth to be ready

### ISSUE THREAD

**Issue by BoogalooLi** [base-org/node#181]
node-geth-1  | INFO [01-26|02:54:59.936] Starting geth on an OP network...        network=base-mainnet
node-geth-1  | INFO [01-26|02:54:59.936] Bumping default cache on mainnet         provided=1024 updated=4096
node-geth-1  | INFO [01-26|02:54:59.936] Enabling metrics collection 
node-geth-1  | INFO [01-26|02:54:59.936] Enabling stand-alone metrics HTTP endpoint address=0.0.0.0:6060
node-geth-1  | INFO [01-26|02:54:59.936] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics
node-geth-1  | INFO [01-26|02:54:59.937] Maximum peer count                       ETH=100 LES=0 total=100
node-geth-1  | INFO [01-26|02:54:59.938] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
node-geth-1  | INFO [01-26|02:54:59.946] Enabling recording of key preimages since archive mode is used 
node-geth-1  | WARN [01-26|02:54:59.946] Disabled transaction unindexing for archive node 
node-geth-1  | INFO [01-26|02:54:59.946] Set global gas cap                       cap=50,000,000
node-geth-1  | INFO [01-26|02:55:00.099] Initializing the KZG library             backend=gokzg
node-geth-1  | INFO [01-26|02:55:00.136] Allocated trie memory caches             clean=1.20GiB dirty=0.00B
node-geth-1  | INFO [01-26|02:55:00.136] Using pebble as the backing database 
node-geth-1  | INFO [01-26|02:55:00.136] Allocated cache and file handles         database=/data/geth/chaindata cache=2.00GiB handles=524,288
node-geth-1  | INFO [01-26|02:55:00.160] Opened ancient database                  database=/data/geth/chaindata/ancient/chain readonly=false
node-geth-1  | INFO [01-26|02:55:00.163] State scheme set to already existing     scheme=hash
node-geth-1  | INFO [01-26|02:55:00.246]  
node-geth-1  | INFO [01-26|02:55:00.246] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
node-geth-1  | INFO [01-26|02:55:00.246] Chain ID:  8453 (Base) 
node-geth-1  | INFO [01-26|02:55:00.246] Consensus: Optimism 
node-geth-1  | INFO [01-26|02:55:00.246]  
node-geth-1  | INFO [01-26|02:55:00.246] Pre-Merge hard forks (block based): 
node-geth-1  | INFO [01-26|02:55:00.246]  - Homestead:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Tangerine Whistle (EIP 150): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Spurious Dragon/1 (EIP 155): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Spurious Dragon/2 (EIP 158): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Byzantium:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Constantinople:              #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Petersburg:                  #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Istanbul:                    #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Muir Glacier:                #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Berlin:                      #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - London:                      #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Arrow Glacier:               #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  - Gray Glacier:                #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md) 
node-geth-1  | INFO [01-26|02:55:00.246]  
node-geth-1  | INFO [01-26|02:55:00.246] Merge configured: 
node-geth-1  | INFO [01-26|02:55:00.246]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md 
node-geth-1  | INFO [01-26|02:55:00.246]  - Network known to be merged: true 
node-geth-1  | INFO [01-26|02:55:00.246]  - Total terminal difficulty:  0 
node-geth-1  | INFO [01-26|02:55:00.246]  - Merge netsplit block:       #0        
node-geth-1  | INFO [01-26|02:55:00.246]  
node-geth-1  | INFO [01-26|02:55:00.246] Post-Merge hard forks (timestamp based): 
node-geth-1  | INFO [01-26|02:55:00.246]  - Regolith:                    @0          
node-geth-1  | INFO [01-26|02:55:00.246]  
node-geth-1  | INFO [01-26|02:55:00.246] --------------------------------------------------------------------------------------------------------------------------------------------------------- 
node-geth-1  | INFO [01-26|02:55:00.246]  
node-geth-1  | INFO [01-26|02:55:00.246] Loaded most recent local block           number=0 hash=f712aa..6c73dd td=0 age=7mo2w1d
node-geth-1  | INFO [01-26|02:55:00.247] Initialising Ethereum protocol           network=8453         dbversion=8
node-geth-1  | INFO [01-26|02:55:00.247] Initialized transaction indexer          limit=0
node-geth-1  | INFO [01-26|02:55:00.247] Loaded local transaction journal         transactions=0 dropped=0
node-geth-1  | INFO [01-26|02:55:00.247] Regenerated local transaction journal    transactions=0 accounts=0
node-geth-1  | INFO [01-26|02:55:00.277] Chain post-merge, sync via beacon client 
node-geth-1  | INFO [01-26|02:55:00.277] Gasprice oracle is ignoring threshold set threshold=2
node-geth-1  | WARN [01-26|02:55:00.279] Engine API enabled                       protocol=eth
node-geth-1  | INFO [01-26|02:55:00.279] Starting peer-to-peer node               instance=Geth/v1.101304.1-stable-ed8e9f54/linux-amd64/go1.20.12
node-geth-1  | INFO [01-26|02:55:00.300] New local node record                    seq=1,706,237,098,675 id=13797d9ff0beb51d ip=<nil> udp=0 tcp=30303
node-geth-1  | INFO [01-26|02:55:00.301] Started P2P networking                   self=enode://416b7b8bb3ab5941f91d7af94c6ee60df3131d9411bc9bc251c9753e535d77f79685e5633707ea3faff0c2587c72477af866ab7b29e2ae27400c5cc3fd5187c7
node-geth-1  | INFO [01-26|02:55:00.301] IPC endpoint opened                      url=/data/geth.ipc
node-geth-1  | INFO [01-26|02:55:00.302] Loaded JWT secret file                   path=/tmp/engine-auth-jwt crc32=0x890e18e0
node-geth-1  | INFO [01-26|02:55:00.303] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
node-geth-1  | INFO [01-26|02:55:00.303] WebSocket enabled                        url=ws://[::]:8546
node-geth-1  | INFO [01-26|02:55:00.303] WebSocket enabled                        url=ws://[::]:8551
node-geth-1  | INFO [01-26|02:55:00.303] HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=*
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready
node-node-1  | waiting for geth to be ready

**Comment by BoogalooLi** [comment]
how to deal with it. thx

**Comment by wbnns** [comment]
@BoogalooLi 

Hello, what are you using for the L1 RPC?

**Comment by BoogalooLi** [comment]
> @BoogalooLi
> 
> Hello, what are you using for the L1 RPC?

my own L1 node, a full node of eth

**Comment by Adewagold** [comment]
waiting for geth to be ready
![image](https://github.com/base-org/node/assets/19472085/44caac44-2a01-4e2f-be2f-d966004b2066)

**Comment by wbnns** [comment]
@BoogalooLi @Adewagold 

Please come to the [Base Discord](https://base.org/discord) and open a #developer-support ticket so we can take a closer look at your docker-compose.yml configurations and also take a closer look at the environments you both are running your nodes in. 👍
