### ISSUE TITLE
Are there new snapshots available?

### ISSUE THREAD

**Issue by wangtao19911111** [base-org/node#182]
Are there new snapshots available?

**Comment by wangtao19911111** [comment]
The latest official snapshot is from October last year. Too old.

**Comment by wbnns** [comment]
@wangtao19911111 

Hi there! Hmm, maybe you have the wrong link? Here are the current snapshots (updated this month): https://docs.base.org/guides/run-a-base-node#running-a-node

**Comment by wangtao19911111** [comment]
Oh my problem. Is there a snapshot of the full node here? The snapshot of the archive node is too large.
