### ISSUE TITLE
Use the eth_sendRawTransaction RPC method and receive the response

### ISSUE THREAD

**Issue by imaiops** [base-org/node#183]
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Post \"https://mainnet-sequencer.base.org\": tls: failed to verify certificate: x509: certificatesigned by unknown authority"}}
How to solve it？ Thanks.

**Comment by wbnns** [comment]
@imaiops 

You should post this to your endpoint for your node or mainnet.base.org (for a single transaction) and it should work; mainnet-sequencer.base.org isn't the right RPC which is contributing to the error.
