### ISSUE TITLE
Application failed

### ISSUE THREAD

**Issue by imaiops** [base-org/node#185]
=2024-02-01T07:58:20+0000 lvl=crit msg="Application failed"                  message="failed to setup: unable to create the rollup node: failed to init L1: failed to validate the L1 config: failed to get L1 genesis blockhash: failed to fetch header by num 17481768: not found"

**Comment by wbnns** [comment]
@imaiops 

Hello, is this on your first, initial sync or did this start occurring after? Are you running using the Docker container?

**Comment by imaiops** [comment]
> @imaiops
> 
> Hi there! Is this on your first, initial sync or did this start occurring after?
> 
> Are you running using the Docker container?

use docker

**Comment by wbnns** [comment]
@imaiops Thanks for the additional information. It looks like it's having a problem connecting to the L1 RPC that was provided; could you please share more details on what you have set up there? Are you running your own L1 or are you using a third-party endpoint?

If you're running your own node, are you able to reach it from the command line and get a successful response from the same environment you're starting the docker container in?

**Comment by gklipel** [comment]
@wbnns do you have any public L1 RPC address?

**Comment by gklipel** [comment]
Nevermind,  I left laziness behind and set up a Prysm node Lol.

**Comment by wbnns** [comment]
@gklipel 

> do you have any public L1 RPC address?

Heya, yes, there are several node providers that offer free plans that you can use:
https://docs.base.org/tools/node-providers/

**Comment by Vtalike** [comment]
> =2024-02-01T07:58:20+0000 lvl=crit msg="Application failed"                  message="failed to setup: unable to create the rollup node: failed to init L1: failed to validate the L1 config: failed to get L1 genesis blockhash: failed to fetch header by num 17481768: not found"

**Comment by wbnns** [comment]
@imaiops 

Heya! Since it has been a while and we haven't heard back, closing this issue for now. If you're still having problems, just let us know and we'll be happy to assist. 👍
