### ISSUE TITLE
L1.beacon question

### ISSUE THREAD

**Issue by orange723** [base-org/node#189]
I find OP_NODE_L1_BEACON in  .env.mainnet
How to find OP_NODE_L1_BEACON url , I need top deploy lighthouse ? write lighthouse host and port to OP_NODE_L1_BEACON ?

help me, give me a example

thanks friend

**Comment by orange723** [comment]
why you can’t put lighthouse write docker-compose.yml

**Comment by fala13** [comment]
I'm also struggling to get node back to sync. 

To be able to connect to your local L1 beacon I guess you need to also add local network visibility in docker by adding in docker-compose.yml:

```
   node:
+    extra_hosts:
+      - "host.docker.internal:host-gateway"
```

so then you could set like
`OP_NODE_L1_BEACON=http://host.docker.internal:8551`

but that also didn't get me running. I use this approach to use my local L1 geth node and this part works 
`OP_NODE_L1_ETH_RPC=http://host.docker.internal:8545`

I also tried setting external beacon node, you can get one from e.g. Ankr: https://www.ankr.com/blog/ethereum-beacon-chain-ankrs-newest-blockchain-rpc-endpoint/

**Comment by orange723** [comment]
But I run eth and lighthouse not this base-node machine，I only run lighthouse base ，will it work？

**Comment by fylsan3** [comment]
Have you solved the problem, brothers?

**Comment by fylsan3** [comment]
Brothers, has the problem been solved?

**Comment by orange723** [comment]
> bro, has the problem been solved?

No，I think trying use nodereal ETH Beacon Chain API now，if success I notify us

**Comment by orange723** [comment]
I running local lighthouse command is 
"lighthouse bn --network mainnet --datadir data --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --port 9006 --port6 9096 --http --http-address 192.168.0.5 --http-port 5053 --http-allow-origin *"

env is OP_NODE_L1_BEACON=http://192.168.0.5:9006

lighthouse tail logs 

"Feb 04 02:54:53.000 INFO Syncing                                 est_time: --, distance: 13144 slots (1 day 19 hrs), peers: 88, service: slot_notifier
Feb 04 02:54:53.000 ERRO Execution endpoint required             info: you need a Capella enabled execution engine to validate blocks, see: https://lighthouse-book.sigmaprime.io/merge-migration.html, service: slot_notifier"

my base node is success runing not error.

But I don't know if after base mainnet upgrade is successful?

**Comment by CryptoSailors** [comment]
Any updates about this issue? I still not able connect my goerli base to the network. 

I got errors like 
```
node-node-1  | t=2024-02-05T11:42:45+0000 lvl=info msg="Initializing rollup node" version=v0.0.0-6de6b5fc-1706738299
node-node-1  | t=2024-02-05T11:43:00+0000 lvl=eror msg="Error initializing the rollup node" err="failed to check L1 Beacon API version: operation failed permanently after 5 attempts: http Get failed: Get \"http://192.3.168.3:9006/eth/v1/node/version\": read tcp 172.27.0.3:50690->192.3.168.3:9006: read: connection reset by peer"
node-node-1  | t=2024-02-05T11:43:00+0000 lvl=crit msg="Application failed"                 message="failed to setup: unable to create the rollup node: failed to check L1 Beacon API version: operation failed permanently after 5 attempts: http Get failed: Get \"http://192.3.168.3:9006/eth/v1/node/version\": read tcp 172.27.0.3:50690->192.3.168.3:9006: read: connection reset by peer"
```

**Comment by fylsan3** [comment]
> I running local lighthouse command is "lighthouse bn --network mainnet --datadir data --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --port 9006 --port6 9096 --http --http-address 192.168.0.5 --http-port 5053 --http-allow-origin *"
> 
> env is OP_NODE_L1_BEACON=http://192.168.0.5:9006
> 
> lighthouse tail logs
> 
> "Feb 04 02:54:53.000 INFO Syncing est_time: --, distance: 13144 slots (1 day 19 hrs), peers: 88, service: slot_notifier Feb 04 02:54:53.000 ERRO Execution endpoint required info: you need a Capella enabled execution engine to validate blocks, see: https://lighthouse-book.sigmaprime.io/merge-migration.html, service: slot_notifier"
> 
> my base node is success runing not error.
> 
> But I don't know if after base mainnet upgrade is successful?

This method is feasible, but it takes a little time to start.

**Comment by orange723** [comment]
> > I running local lighthouse command is "lighthouse bn --network mainnet --datadir data --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --port 9006 --port6 9096 --http --http-address 192.168.0.5 --http-port 5053 --http-allow-origin *"
> > env is OP_NODE_L1_BEACON=http://192.168.0.5:9006
> > lighthouse tail logs
> > "Feb 04 02:54:53.000 INFO Syncing est_time: --, distance: 13144 slots (1 day 19 hrs), peers: 88, service: slot_notifier Feb 04 02:54:53.000 ERRO Execution endpoint required info: you need a Capella enabled execution engine to validate blocks, see: https://lighthouse-book.sigmaprime.io/merge-migration.html, service: slot_notifier"
> > my base node is success runing not error.
> > But I don't know if after base mainnet upgrade is successful?
> 
> This method is feasible, but it takes a little time to start.

Really？I success running base node，but I don't know is right

**Comment by CryptoSailors** [comment]
Finaly i launch my goerli node. So. The my configuration is:

Lighthouse
```
ExecStart=/home/ethereum/.cargo/bin/lighthouse bn \
 --network goerli \
 --port 9006 \
 --port6 9096 \
 --http \
 --http-address 188.3.188.3 \
 --http-port 5053 \
 --http-allow-origin "*" \
 --execution-endpoint http://localhost:8551 \
 --execution-jwt /home/ethereum/lighthouse/jwt.hex \
 --disable-deposit-contract-sync \
 --checkpoint-sync-url=https://prater-checkpoint-sync.stakely.io
 ```
 In my `env.goerli` i input
```
 OP_NODE_L1_BEACON=http://188.3.188.3:5053
```

And it start sycnh.

**Comment by fylsan3** [comment]
```
#!/usr/bin/env bash
nohup /data/base/light/run/lighthouse bn \
--network=mainnet \
--execution-endpoint http://eth-L1:8551 \
--execution-jwt /data/base/light/run/secrets/jwt.hex \
--datadir=/data/base/light/run/data \
--checkpoint-sync-url https://mainnet.checkpoint.sigp.io \
--port=9000 \
--http \
--http-address=0.0.0.0 \
--disable-deposit-contract-sync \
--http-port=4000   >> /data/base/light/run/sync.log &
```
This is my startup method, and then my base specifies this service and it can be synchronized normally.

**Comment by fala13** [comment]
> This is my startup method, and then my base specifies this service and it can be synchronized normally.
@fylsan3, could you please share what is your exact OP_NODE_L1_BEACON flag value? I'm trying every combination with my nimbus (latest) and geth (v1.13.4) but I always `temp: failed to fetch receipts of L1`.

**Comment by wbnns** [comment]
@fala13 

Hello, the `OP_NODE_L1_BEACON` value will be the address of the endpoint. It will change for each node operator. If you're still having trouble setting this, please come to the [Base Discord](https://base.org/discord) and open a #developer-support ticket, we can help you there. 👍

@orange723 @CryptoSailors 

The Base Goerli testnet is now deprecated, so it will no longer be possible to sync. That said, Sepolia should be possible without issue. If you all have any other questions or issues, please let us know.
