### ISSUE TITLE
Base always 12hours behind. Sync Issue

### ISSUE THREAD

**Issue by pikansj0s** [base-org/node#192]
Hi.. How can I get my base node in sync? I am running the latest versions/updates as of today. But my base node is always 12 hours behind... Has been like that for 7 days now.

node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="ignoring batch with mismatching parent hash" batch_index=0 batch_timestamp=1,707,202,215 parent_hash=0x83e580026acc309c721b9ec809b0a508d0311d2e82357bfd47f7431b172ade86 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=12   current_safe_head=0xa147efff833e47efb1e0a0a9afff810f0c7761ae390491fe58877da8fdd45d71
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="dropping batch"                         batch_timestamp=1,707,202,215 parent_hash=0x83e580026acc309c721b9ec809b0a508d0311d2e82357bfd47f7431b172ade86 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=12   l2_safe_head=0xa147efff833e47efb1e0a0a9afff810f0c7761ae390491fe58877da8fdd45d71:10206433 l2_safe_head_time=1,707,202,213
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Generating next batch"                  epoch=0x36a42a07137fc3ccb04391bb6ac859d7f71220130be7b6a0b3e9cdd8097e4b36:19167527 timestamp=1,707,202,215
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="generated attributes in payload queue"  txs=1    timestamp=1,707,202,215
geth-1  | INFO [02-06|18:59:44.545] Starting work on payload                 id=0x9d250df43fbd6a41
geth-1  | INFO [02-06|18:59:44.548] Imported new potential chain segment     number=10,206,434 hash=c7fb48..0b2fb7 blocks=1 txs=1   mgas=0.047  elapsed="826.904µs" mgasps=56.733   age=12h9m29s  dirty=0.00B
geth-1  | INFO [02-06|18:59:44.548] Chain head was updated                   number=10,206,434 hash=c7fb48..0b2fb7 root=6aa562..4a662e elapsed="56.021µs"  age=12h9m29s
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="inserted block"                         hash=0xc7fb488b5c0b9dc1fd9afd565f82cd5e22a6b4a9925c095077d9b568ba0b2fb7 number=10,206,434 state_root=0x6aa562bd803edb638086a7c7bb6c9b153ef3e0714ec03cff1d695c1e8e4a662e timestamp=1,707,202,215 parent=0xa147efff833e47efb1e0a0a9afff810f0c7761ae390491fe58877da8fdd45d71 prev_randao=0x167b695f87e3fcee38ff50657d6120d23bb3d507e64692147c0ede6f336d2e68 fee_recipient=0x4200000000000000000000000000000000000011 txs=1    update_safe=true
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Sync progress"                          reason="processed safe block derived from L1" l2_finalized=0x4fe2a4ca7fb15c925511a9b7133de5ada40194d5dbbe15d73b88e56938817d3e:10205783 l2_safe=0xc7fb488b5c0b9dc1fd9afd565f82cd5e22a6b4a9925c095077d9b568ba0b2fb7:10206434 l2_unsafe=0xc7fb488b5c0b9dc1fd9afd565f82cd5e22a6b4a9925c095077d9b568ba0b2fb7:10206434 l2_time=1,707,202,215 l1_derived=0x9ba830b44a1c8404daecaa9fa230fd421099abcf16d1cdf9dba8ce7c89796c84:19171127
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="ignoring batch with mismatching parent hash" batch_index=0 batch_timestamp=1,707,202,217 parent_hash=0x2c3701f444dcf92d4e2d4d67a73133b2df6aa6decb342542d82866f58af86ce3 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=13   current_safe_head=0xc7fb488b5c0b9dc1fd9afd565f82cd5e22a6b4a9925c095077d9b568ba0b2fb7
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="dropping batch"                         batch_timestamp=1,707,202,217 parent_hash=0x2c3701f444dcf92d4e2d4d67a73133b2df6aa6decb342542d82866f58af86ce3 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=13   l2_safe_head=0xc7fb488b5c0b9dc1fd9afd565f82cd5e22a6b4a9925c095077d9b568ba0b2fb7:10206434 l2_safe_head_time=1,707,202,215
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Generating next batch"                  epoch=0x36a42a07137fc3ccb04391bb6ac859d7f71220130be7b6a0b3e9cdd8097e4b36:19167527 timestamp=1,707,202,217
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="generated attributes in payload queue"  txs=1    timestamp=1,707,202,217
geth-1  | INFO [02-06|18:59:44.550] Starting work on payload                 id=0x8c8fe6fe504c3770
geth-1  | INFO [02-06|18:59:44.553] Imported new potential chain segment     number=10,206,435 hash=d5ca46..ada505 blocks=1 txs=1   mgas=0.047  elapsed=1.180ms     mgasps=39.756   age=12h9m27s  dirty=0.00B
geth-1  | INFO [02-06|18:59:44.554] Chain head was updated                   number=10,206,435 hash=d5ca46..ada505 root=18b74c..fd9731 elapsed="56.972µs"  age=12h9m27s
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="inserted block"                         hash=0xd5ca4625191dd24075a57613eff6003ffe184997ffcbb7b2c42c7e47e7ada505 number=10,206,435 state_root=0x18b74cad0ed144f015c006c321d8259298dd3714a3d9660e6e1fc4c92cfd9731 timestamp=1,707,202,217 parent=0xc7fb488b5c0b9dc1fd9afd565f82cd5e22a6b4a9925c095077d9b568ba0b2fb7 prev_randao=0x167b695f87e3fcee38ff50657d6120d23bb3d507e64692147c0ede6f336d2e68 fee_recipient=0x4200000000000000000000000000000000000011 txs=1    update_safe=true
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Sync progress"                          reason="processed safe block derived from L1" l2_finalized=0x4fe2a4ca7fb15c925511a9b7133de5ada40194d5dbbe15d73b88e56938817d3e:10205783 l2_safe=0xd5ca4625191dd24075a57613eff6003ffe184997ffcbb7b2c42c7e47e7ada505:10206435 l2_unsafe=0xd5ca4625191dd24075a57613eff6003ffe184997ffcbb7b2c42c7e47e7ada505:10206435 l2_time=1,707,202,217 l1_derived=0x9ba830b44a1c8404daecaa9fa230fd421099abcf16d1cdf9dba8ce7c89796c84:19171127
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="ignoring batch with mismatching parent hash" batch_index=0 batch_timestamp=1,707,202,219 parent_hash=0xaf9d81adc8ffdc289de4809beecf051be080ee5fb7bf26b5a661e656dfab66b6 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=11   current_safe_head=0xd5ca4625191dd24075a57613eff6003ffe184997ffcbb7b2c42c7e47e7ada505
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="dropping batch"                         batch_timestamp=1,707,202,219 parent_hash=0xaf9d81adc8ffdc289de4809beecf051be080ee5fb7bf26b5a661e656dfab66b6 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=11   l2_safe_head=0xd5ca4625191dd24075a57613eff6003ffe184997ffcbb7b2c42c7e47e7ada505:10206435 l2_safe_head_time=1,707,202,217
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Generating next batch"                  epoch=0x36a42a07137fc3ccb04391bb6ac859d7f71220130be7b6a0b3e9cdd8097e4b36:19167527 timestamp=1,707,202,219
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="generated attributes in payload queue"  txs=1    timestamp=1,707,202,219
geth-1  | INFO [02-06|18:59:44.557] Starting work on payload                 id=0xf1cec499c0ddbe1f
geth-1  | INFO [02-06|18:59:44.559] Imported new potential chain segment     number=10,206,436 hash=a8ceb9..d59b08 blocks=1 txs=1   mgas=0.047  elapsed="685.66µs"  mgasps=68.420   age=12h9m25s  dirty=0.00B
geth-1  | INFO [02-06|18:59:44.560] Chain head was updated                   number=10,206,436 hash=a8ceb9..d59b08 root=0fe599..3ac567 elapsed="113.784µs" age=12h9m25s
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="inserted block"                         hash=0xa8ceb9b9ea8dd5f23f0a145ff3a4cb169518dbf72e48256da7a0000772d59b08 number=10,206,436 state_root=0x0fe599e1093e265d6e2dc10807fdefb0acaaffc87537b5e42e0592bae93ac567 timestamp=1,707,202,219 parent=0xd5ca4625191dd24075a57613eff6003ffe184997ffcbb7b2c42c7e47e7ada505 prev_randao=0x167b695f87e3fcee38ff50657d6120d23bb3d507e64692147c0ede6f336d2e68 fee_recipient=0x4200000000000000000000000000000000000011 txs=1    update_safe=true
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Sync progress"                          reason="processed safe block derived from L1" l2_finalized=0x4fe2a4ca7fb15c925511a9b7133de5ada40194d5dbbe15d73b88e56938817d3e:10205783 l2_safe=0xa8ceb9b9ea8dd5f23f0a145ff3a4cb169518dbf72e48256da7a0000772d59b08:10206436 l2_unsafe=0xa8ceb9b9ea8dd5f23f0a145ff3a4cb169518dbf72e48256da7a0000772d59b08:10206436 l2_time=1,707,202,219 l1_derived=0x9ba830b44a1c8404daecaa9fa230fd421099abcf16d1cdf9dba8ce7c89796c84:19171127
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="ignoring batch with mismatching parent hash" batch_index=0 batch_timestamp=1,707,202,221 parent_hash=0xb077a9e1d9947557aba6d754a227d124fed0af37fcc38aa8d8efa604b6cb91d8 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=7    current_safe_head=0xa8ceb9b9ea8dd5f23f0a145ff3a4cb169518dbf72e48256da7a0000772d59b08
node-1  | t=2024-02-06T18:59:44+0000 lvl=warn msg="dropping batch"                         batch_timestamp=1,707,202,221 parent_hash=0xb077a9e1d9947557aba6d754a227d124fed0af37fcc38aa8d8efa604b6cb91d8 batch_epoch=0xd1430c8014aeb11e405fe39fa7a0a2dc7e41127d783a2df33af80e22e4ad0513:19167512 txs=7    l2_safe_head=0xa8ceb9b9ea8dd5f23f0a145ff3a4cb169518dbf72e48256da7a0000772d59b08:10206436 l2_safe_head_time=1,707,202,219
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="Generating next batch"                  epoch=0x36a42a07137fc3ccb04391bb6ac859d7f71220130be7b6a0b3e9cdd8097e4b36:19167527 timestamp=1,707,202,221
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="generated attributes in payload queue"  txs=1    timestamp=1,707,202,221
geth-1  | INFO [02-06|18:59:44.562] Starting work on payload                 id=0x7cef91f935753a23
geth-1  | INFO [02-06|18:59:44.564] Imported new potential chain segment     number=10,206,437 hash=0c3b5d..cbba96 blocks=1 txs=1   mgas=0.047  elapsed="754.592µs" mgasps=62.170   age=12h9m23s  dirty=0.00B
geth-1  | INFO [02-06|18:59:44.565] Chain head was updated                   number=10,206,437 hash=0c3b5d..cbba96 root=22a6ef..732f81 elapsed="89.463µs"  age=12h9m23s
node-1  | t=2024-02-06T18:59:44+0000 lvl=info msg="inserted block"                         hash=0x0c3b5d1be6a1f41c3c197831b9ebb0d98db7930a01c01f5403257493e0cbba96 number=10,206,437 state_root=0x22a6ef933ace72fed8884b197a30ab7f5f56029bded143139027b78acc732f81 timestamp=1,707,202,221 parent=0xa8ceb9b9ea8dd5f23f0a145ff3a4cb169518dbf72e48256da7a0000772d59b08 prev_randao=0x167b695f87e3fcee38ff50657d6120d23bb3d507e64692147c0ede6f336d2e68 fee_recipient=0x4200000000000000000000000000000000000011 txs=1    update_safe=true

**Comment by MrFrogoz** [comment]
workaround https://github.com/base-org/node/issues/127#issuecomment-1892634824

**Comment by wbnns** [comment]
@pikansj0s 

Hello, thanks for reporting -- let's consolidate this into the conversation in #127.
