### ISSUE TITLE
Base mainnet: failed to check L1 Beacon API version

### ISSUE THREAD

**Issue by AlexanderBarkovsky** [base-org/node#211]
Hello everyone! I have started base full-node with .env.mainnet on my server following instruction on github but got error:

`t=2024-03-02T15:56:47+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE_L2_ENGINE_AUTH_RAW=688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a"`
`t=2024-03-02T15:56:47+0000 lvl=warn msg="Found a deprecated flag which will be removed in a future version" flag_name=beta.extra-networks`
`t=2024-03-02T15:56:47+0000 lvl=warn msg="The beta.extra-networks flag is deprecated and can be omitted safely."`
`t=2024-03-02T15:56:47+0000 lvl=eror msg="Cannot configure network and rollup-config at the same time.\nStartup will proceed to use the network-parameter and ignore the rollup config.\nConflicting configuration is deprecated, and will stop the op-node from starting in the future.\n" network=base-mainnet rollup_config=mainnet/rollup.json`
`t=2024-03-02T15:56:48+0000 lvl=info msg="Rollup Config" l2_chain_id=8453 l2_network=Base l1_chain_id=1 l1_network=mainnet l2_start_time=1686789347 l2_block_hash=0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd l2_block_number=0 l1_block_hash=0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771 l1_block_number=17481768 regolith_time="@ genesis" canyon_time="@ 1704992401 ~ Thu Jan 11 17:00:01 UTC 2024" delta_time="@ 1708560000 ~ Thu Feb 22 00:00:00 UTC 2024" ecotone_time="@ 1710374401 ~ Thu Mar 14 00:00:01 UTC 2024" fjord_time="(not configured)" interop_time="(not configured)"`
`t=2024-03-02T15:56:48+0000 lvl=info msg="Initializing rollup node" version=v1.7.0-f7078830-1708633578`
`t=2024-03-02T15:57:03+0000 lvl=eror msg="Error initializing the rollup node" err="failed to check L1 Beacon API version: operation failed permanently after 5 attempts: failed request with status 404: "`
`t=2024-03-02T15:57:03+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node: failed to check L1 Beacon API version: operation failed permanently after 5 attempts: failed request with status 404: "`

My .env.mainnet is default except variables OP_NODE_L1_ETH_RPC and OP_NODE_L1_BEACON. There are links to my geth archive node, that works well. How I can fix it or check that my L1 node is fittable for base node?

**Comment by roberto-bayardo** [comment]
What are you setting OP_NODE_L1_BEACON to?  Looks like this is pointing to some other sevice than the L1 http RPC port.

**Comment by AlexanderBarkovsky** [comment]
I am setting OP_NODE_L1_BEACON to my geth mainnet node with flag --gcmode=archive. And it works well. And I can send json-rpc requests there. 

OP_NODE_L1_BEACON=http://geth.mainnet-archive.***.io

For example, output of request:

`curl -H "Content-type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://geth.mainnet-archive.***.io`

`{"jsonrpc":"2.0","id":1,"result":{"baseFeePerGas":"0x17baf65f85","difficulty":"0x0","extraData":"0xd883010d0e846765746888676f312e32312e37856c696e7578","gasLimit":"0x1c9c380","gasUsed":"0x639ab8","hash":"0xd6a3e2de3df02516d13b08e80dc4415243bc999f1b04a0632f59f485ce737a72","logsBloom":"0x46014902200004c95078010c00001414520204018403500200400131090020d044041440080800028401310804043194420b708a89202480180002304528a21040615809080000386c0840a8500036004010180508e80c6518821210e02104260a000c4002fe40012d10408821080888a1102060cd000c040240049501084204808120400440595540a0d010030ca204c000040105290000041121104a14206e02040440088032810118009080008c0624400c00020e100422c02c020303e0520000c2e20102214944060140144855450040442282120e4448098c0a0083302bca502425880285140040006382200a2c81003210010007c9420838544ae00581","miner":"0x388c818ca8b9251b393131c08a736a67ccb19297","mixHash":"0xac63117c52aa2b04f5a2fc1f450fa2984f8ae00af5c339db6bc8d7c3fe304416","nonce":"0x0000000000000000","number":"0x12768d7","parentHash":"0x02455fddbaab8a7b9f702d675c320dbd89bd9d7aabf44b8a0a18c8585584db74","receiptsRoot":"0x2fba466466da7d1ea81b81747564549340237f70a3666c99b318bd482775d110","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x4daf","stateRoot":"0x88b8ae98e52808455131b1ca571fcd7cff51323fded30c54b8de3aa3446238db","timestamp":"0x65e567af","totalDifficulty":"0xc70d815d562d3cfa955","transactions":["0xbe64464ab9d2265e866d47cc07c9304084e5672b19118b5855ecf7261a73699b","0xecca0ba0c25ecd440d1a2f4044b61170443493636f2261d429f3c1be00ee9a17","0xc75d3a0fa673daaedc20b9c44a4d76f03f2eb65118e9ec07683fc39d66aef925","0xeb38ce5e45d7f6295c3332276e5e059635dba3b569270c024c0d0582df004f43","0x3d79694d2a44c1daeb43fc9287fbfdd77748ed2fa83355c0b34b24f413f21efb","0xa8fdcadea9c0a059481ae1e71d0cb418aee5630cebf4dc2f92faf7baf73bcc88","0x066829b846b450ae30baa16877a42773a8f6c3f616ef4f97e2ef31019f09a449","0x9768cd1e45a2b631a4d95dcca93732dd6d40563718fc23915074d1a9ae3b4b89","0x4a607d69076711ccc50b446581d0b5bb5db22b2a0c8876cc28fc73d48ec45762","0x537c85f1112804472e209fe0091783b0ff9ac239bd499f25c0c65ce0342e6ead","0xe3f27a3161c4794322cdddacd808468d7b8899e3d928f80719cb6ef0ba6fa5a1","0x9f9442b8b6ec082de750a11f01a9a1d63fbfbf1781f2f17f13f52e49ad5fbc08","0x59d6d9e0c75bad92ce7372ffdea58e6829b8df24ec3cb790ae977e7339bc7922","0xba6b1037a7d03e8910ed58cc637c17b9892851004953ead9a1191a0137320c1a","0xe00f71e979083e56619121b30b299327340f2b3e7edbf6e7b6b2ba0e3de04888","0x5042cd1122757b92a39cfd69c46e8082f3c20de68b6435ce23497d9e54cb8918","0x11088c8143387fc860afa42014ce0f9e8180f8e7aa8bf8f91bca7002c4d3f8fc","0x11d41624c6add3771c4a8528d015ba69baa3f13955127d68747e338fbb202a97","0x180ea50b1b5da14a916068735f170be1d8c8daa0e70db520116698517c1d168b","0xe342dded39296e64c2ba318d7dd0c296c625ced210ae25c61af5d91a273dc2fd","0x5b393d9bc5b6156896436017ac679484ced786f7b99dc761e878f4f1bafc1ec7","0xb0fb9a57ac33ceb8e297c4f172449067dcf2b56bd4dd0dc98bfb83023bd9b05f","0x7fb8c8f0a592dc3eef1c56ff78597697b96e8b8995334ff3ec00d371581a1e86","0xd0a84f36a35538a3746f4ac24b25c73cdf5b5ef9c9c5c235bbbd5a8ff839be05","0xf8b44d6c9232e7f697eea70fc202cfa15d2f01abcbb680c70bcf9c4c763bd031","0x95d679b398e484922739187ea096ccb36d0c8613716e4fc9ed69bc2ac4e05bb5","0xbb05eab07f73f196b43bd3d03d6b349e1331eb486fb460d57ad1c1dd9aede6f2","0x5de566f48a5378175a30b69f827e8ae322bdf4549bf09ced306e2f101d0c2dd2","0x5f148665c357bdc6d254b1f07c4c4b098d1e1c11317164d3b979014401008806","0x9622e22692ec98a2d275958af2d2f4dc9e4d49facd1a097ebb8930cce984688f","0x6cb494a3b4fda1335a6b34dcb34b8c58dd1711d1f383594f9508629c517353fc","0x2e8ea40b6fce9bc2ed18eb2eec435a221da52e10431d24cffc2d8f08a8d2564f","0xbdcf8e05eb81089d14746156e81dcb4ff32e009c04a6acf24ddaa08427e43ab8","0x0343b62ec4386b6ff001dea48475ef44556439a4ff1f9b3bfd7d577406e9a335","0x5c9de691f5496197ace81bd2fccd644c8163bb2e18e95f2341a0ba20e9abaee0","0x388f834c2f11ab94ceaa088bc8abcfc5fd098b472eecda06c3bc4db644b25043","0x7f4acb47d5b56a703c15ec44528fe3b94c415e8c25aac7da22074e42bb1d82f8","0xa4019e666b07fc3d7cee581093dc4bb4ec9f1a83796388c502becc3b38013458","0xef20114bf42750ea9a4a85c4114b7c173a216f22e4f67198d6ba6d463a6539ab","0x7477631c406928d1f70b3ccffd20f11c528ed8573862bf82098ab3e2d0097123","0x31590f233f1d4f0ec1a132bdb78814e29034da363d329913415c642766eb8301","0xa7af2c4e1ff8794b2bb7750bd3b22849de3663d9bd319aa140fee6360f6a01a5","0x4a4f1e9c2df1e282bdc34ea9881447a515483aaee214eac5793e8fdcf63c892c","0x9923284633c738e9a386cb772862ad74ffe435b16519c8011530057789ffe787","0x1df56676570ebfab754856eca56a9329c48d7edd84e71dbc6a11d15ec8a9099f","0x0fb96cd091573cfb36e32f61704fce5e6bc60b8a24a9f5a6a0ca565b2cecbea5","0x18f2e24986d5211e8893016fd73f928a1cf611114903c0dfb71105659e7db55e","0x74942ed3f91c6918df012a6caa16e023f41519704713e082defc862ea2bd4b31","0x11668580fdd52153dac67aed81c935535ec94e5b76e7543da794b84d972d4cae","0x0d4013a606eb51e0f3fe68b3949935f74920ed07bef4310f6bbd174db75729dc","0xf6667965cd746f908437e505393a7bbb7e8706973fcde4e01e0ad517733e6bcb","0x5a130a1497d78a95a5278ad73f054d91c66c4541c9f6c8f334979e050d1269bb","0x2a8bc0025dff6aeee227e3db54964a92cf9cd677d2210455e0ec4dc5f44f6468","0x10c90f0c84c92b7a0e5eb93dca674e6730cbd5b96be8921839622665193eac73","0x9cee6db32527081f8b3cf0b57d0e2a9eb4fba62978f13f35b3c6e2a7bc64d4a4","0x46b242672d0581da63235c04154a63b373e542f332d7c50a14f51e0edd5748ee","0x045ad3d176819b12e9d9af5d7c780f26a09791877c94515238e91b0cd673e513","0xa2e83c96a3a65bee906cb0a4e0fb73e910f69453e202a5ff98e7555c16d81308","0xacd318e88599bf591549521a51a1c209e44a13ac7213ac4438d3a6e8a5fffb88","0x3fcfbe08b12137538e8d7462579a7b4c5869d4cfffc2f56c4ce18e4ee2893fb5","0x3f54d28058920713382d996e7e9d6be280847c2c3f6cff70e35fe82c528b4bf8","0x621e64c53a2e10a40b5d398418feda2fdedcc62c5301f247e9b456838bc0c51d","0xe4eb21757ee77bfe36a0394ab62ea65ba0585b967deb40665458298f2eaba87a","0xee8b7b80d8806fdd3a6f97ddff750cb92e8ece14c2ee7fea5f37d1f47fd59283","0x48b10549450f041cb243a66884c422de481c81d37da91110f09dad4266b11ffa","0xd3396122c14e81864c3f1a5185c2c073bd4a268f78c0e2270f6beb03b2e1c215","0xc29488c714f81f4ac950298bb351383c7e5f55c5dc91cc8e9f66f30a3b15cab6","0xd8fc6dee98eeff3405c3b37dfce9fd5979eb7aafaa43c4a656602d265fa57059","0x23b34e0c019ad7f46f6c4268882d570a6a2a743a1d4f6eecaf478174fc46cbc7","0x0ec7f57926cfc5fada9dd33d34bf059af76aacc40321df35baf3fb70f033ab12","0x1d195d9f0e06514e70e240f2f5a77477cfba7d64d8e99217b55f9b065ac7c223","0x0a43335af47389add7dbf6901a84be86a31c1ab1047500c267adf1a034fa7e2d","0x5bd0692545d70150dbfb17456f37da76b8adf4ca171fdcb51177bee5d1f3ae2e","0xa98afa1e8403a70607b9bae80060073fb57c9dcb6fdf173a603d8852edc4ddd7","0xc6ad4a39de5cfa539d09ab154250a0fc57ea38193923c62bd7cfeb4f388b5a07","0xff3c21e5fa6314e0c932d46ff4eaceda8221cde4188ada27007f90a4304d9db3","0xdf72f7871f87f56773983def2076479ff23e162baefccd822ac6d6117650ca76","0x75d51bae60463230abfbd900128132df621b49e291e8741f701452eb6a6277a4","0xcc6cf6eb6e947033dfd1036a9bbd532743ab5f71fb51ede487fb5ac1042e0aca","0xecef1d9635a45471d27af39a26e2f47600306c961f47a2481617f574bd1db976","0x6f4f10ca2dbb22f20f0da64d9ec3069ca519299af8cbcc61cc2dfef9811d20c5","0x60f08ffbdf371538fc30972bfc971deee2bd3cf9ef5c7e5da6fbf339f18c221f","0x776a6ae7fb014defd1be2522cd8dbf1e9cce1f20ca502732b47748b6f33047d2","0xd43ee6eee4f379a9906f9cf8cd2ccf42b4653b19ff536c78b2c0d78917d3b3dd","0x3676851e624fec55db49922711236c90a17a9368d154859b15e5c7d71cf27ebf","0x9462cc74b65dc1a7242919f4a99c7ff5925f1a48415fbecabf333b4f5a3db00f","0x86c12a2d59dc39e8d7d7cba4c508af4670433fca9b89bf54ce07ca597d9eb3ec","0x94dbae59f41f7f701870b9243f8653c954f3815bccbba813da764264251d9954","0xd4a552fd74268707f87926df563c07cbb8767ab93336b08dde2aa091d595347e","0xa7cbccc2ba38065d44493841b07a742713108de9fed692b57c65efad40107d48","0x069e59ea36548b66062ef9e354f83282812512702b2c33a45f70544898e99695","0x81c34693d71ddf311996cc209d6b83af76d794b2bfd6bf9c7df1658951e09e9d","0xb660b6ad34c7782db9b5725ccba5b76134e445f04c7adad9172873653223f34a","0x3252909830a76fcb3ccfe18ae90f543acb4464168621a2d477871faa134245fa","0x2bcd5e69e5136895bcafef5b816a9490f779695015b26811a6d812da70cbd0e0","0x04af1455462cc09dfdf6cb0297cac3912b6ffe3fe9da7154f522cd542527f4b4","0xa55b39067441a7d3b8419558c46ae01d916036c86f3e9028706851edef8e1aeb","0x0ffbc1d259e397b9802f05cc9135ab47dd4739785fa056e355db2cdd68e331d8","0xf7289fc2bbf3d3b19ac55e186ba6f7253146d614f5fc305609e6b9cf1a08c67a","0x01c1b2eb4d721a0a2649def51946bf8f0e35de1c75310d1dddf7cecd543f1b45","0xece439e2fad874ad52637d1d02e0fae7b8270bda44cc81b142f7d4aca0195eb3","0x9a49cdd0237c8d23c8395dab1dfd222c23c317ce98914185f7fefdefa090c35d","0xbb6bb60932f00b29de88cd0761a601367d49e85d6d29860aa10fc581c51234c6","0xebeace1de4f01b28b2e867bc4057602beb802696c1086784a600d39267fc3751","0x897776bf3eff2068deb2485adef7ef84933197d35b724fc64299b44852f90b9b","0xff010f155d98831214c2f4993a3c8405364d13230d0a5396eac162c5fff22c55","0xbfddda464884cfc351700c279b3821ce12afa59ec1e0c775c37a083885bb0950"],"transactionsRoot":"0x65945aae0fa0b8a46bf8b59de82f2b4a510068dd569942550808b63836d6a05e","uncles":[],"withdrawals":[{"index":"0x237a066","validatorIndex":"0x11dacf","address":"0x70d5ccc14a1a264c05ff48b3ec6751b0959541aa","amount":"0x1142a89"},{"index":"0x237a067","validatorIndex":"0x11dad0","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x113a768"},{"index":"0x237a068","validatorIndex":"0x11dad1","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x112665d"},{"index":"0x237a069","validatorIndex":"0x11dad2","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x113ab13"},{"index":"0x237a06a","validatorIndex":"0x11dad3","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x11239b4"},{"index":"0x237a06b","validatorIndex":"0x11dad4","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x11315ef"},{"index":"0x237a06c","validatorIndex":"0x11dad5","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x113e90b"},{"index":"0x237a06d","validatorIndex":"0x11dad6","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x11267fe"},{"index":"0x237a06e","validatorIndex":"0x11dad7","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x113b547"},{"index":"0x237a06f","validatorIndex":"0x11dad8","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x112cd66"},{"index":"0x237a070","validatorIndex":"0x11dad9","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x1138b10"},{"index":"0x237a071","validatorIndex":"0x11dada","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x112ccec"},{"index":"0x237a072","validatorIndex":"0x11dadb","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x1123a9b"},{"index":"0x237a073","validatorIndex":"0x11dadc","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x112d513"},{"index":"0x237a074","validatorIndex":"0x11dadd","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x113f458"},{"index":"0x237a075","validatorIndex":"0x11dade","address":"0x8e609ac80f4324e499a6efd24f221a2caa868224","amount":"0x11316d7"}],"withdrawalsRoot":"0xd44d02db66b9f5779dbd842fce8d881f5237691c730567cd5e66513a679d12ce"}}`

**Comment by roberto-bayardo** [comment]
the BEACON NODE needs to point to the consensus client (e.g. prysm, lighthouse, etc..) not geth.

**Comment by AlexanderBarkovsky** [comment]
Oh, really! My fault! I have changed the endpoint to the beacon node and everything is fine now. Thanks! I'll be more careful next time)
