### ISSUE TITLE
updated to v0.7.0 after the error,cannot unmarshal hex number with leading zero digits into Go struct field StorageProofEntry.storageProof.value of type *hexutil.Big"

### ISSUE THREAD

**Issue by yuanwj210** [base-org/node#213]
![image](https://github.com/base-org/node/assets/85926598/bbfe8c7f-e014-4464-9a49-72319b44d4ae)

**Comment by wbnns** [comment]
Heya, please upgrade to 0.8.1. https://github.com/base-org/node/releases/tag/v0.8.1

If this doesn't resolve the issue, it would be best to join the [Base Discord](https://base.org/discord) and open a #developer-support ticket. We can take a closer look at your configuration there! 👍
