### ISSUE TITLE
URL format of L1 Beacon API endpoint

### ISSUE THREAD

**Issue by hippke** [base-org/node#220]
I have been running my own Base node for some months without issues. I run prysm+geth for Ethereum and then op-geth and op-node on top for Base. It's in an LXC not in Docker but that shouldn't matter for this question.

Since the Dencun update some days ago, it stopped running. I updated all binaries and Ethereum runs well again. Op-node however fails. It requested to set the  `--l1.beacon` parameter which I did as `--l1.beacon=http://localhost:3500`. But when starting Op-node I get the error: 

> Application failed                       message="failed to setup: unable to create the rollup node config: misconfigured L1 Beacon API endpoint: expected L1 Beacon API endpoint, but got none"

As a test, calling `wget http://127.0.0.1:3500/eth/v1/beacon/states/finalized/root` works from prysm side.

What is the correct endpoint setting? I assume it is something like: `wget http://127.0.0.1:3500/eth/v1/beacon/SOMETHING` ?

**Comment by wbnns** [comment]
@hippke 

Hi there! Apologies, I don't believe we officially support / have documentation or guidance for LXC. Would it be possible to temporarily try it from a Docker container to ensure that the Base Node is actually able to reach the endpoint (e.g. localhost:3500)?

**Comment by chief-r0cka** [comment]
> I have been running my own Base node for some months without issues. I run prysm+geth for Ethereum and then op-geth and op-node on top for Base. It's in an LXC not in Docker but that shouldn't matter for this question.
> 
> Since the Dencun update some days ago, it stopped running. I updated all binaries and Ethereum runs well again. Op-node however fails. It requested to set the `--l1.beacon` parameter which I did as `--l1.beacon=http://localhost:3500`. But when starting Op-node I get the error:
> 
> > Application failed                       message="failed to setup: unable to create the rollup node config: misconfigured L1 Beacon API endpoint: expected L1 Beacon API endpoint, but got none"
> 
> As a test, calling `wget http://127.0.0.1:3500/eth/v1/beacon/states/finalized/root` works from prysm side.
> 
> What is the correct endpoint setting? I assume it is something like: `wget http://127.0.0.1:3500/eth/v1/beacon/SOMETHING` ?

Hello @hippke , you might check my answer here, I think it might help you  solve your problem:
https://github.com/base-org/node/issues/224#issuecomment-2038569965

**Comment by wbnns** [comment]
@hippke 

Hi there! Since it's been a while without an update I'm going ahead and closing this issue. That said, if you're still having a problem, please let us know and we can reopen or connect on Discord to take a closer look. 👍
