### ISSUE TITLE
Indexation stuck

### ISSUE THREAD

**Issue by germashevanton** [base-org/node#221]
Base Node was syncing fine, after updating ETH mainnet node, indexation stuck, noticed such errors in logs. Mainnet node fully synced for now. 

base-node-geth-1 | WARN [03-17|17:10:13.494] Served engine_forkchoiceUpdatedV1        conn=172.20.0.92:54724 reqid=4967 duration="176.79µs" err="Invalid parameters" errdata="{Error:forkChoiceUpdateV1 called post-shanghai}"
base-node-node-1 | t=2024-03-17T17:10:13+0000 lvl=warn msg="Failed to share forkchoice-updated signal" state="&{HeadBlockHash:0xfb4fa24c05dc997d04642b0894da69a85ae4ade174b0d7cbd8086bc7b42bebf9 SafeBlockHash:0xfb4fa24c05dc997d04642b0894da69a85ae4ade174b0d7cbd8086bc7b42bebf9 FinalizedBlockHash:0xc8752fcadcb629d30d304078641275b968bd33a9290b654c131af986e23f93fe}" err="Invalid parameters"
base-node-node-1 | t=2024-03-17T17:10:13+0000 lvl=warn msg="Derivation process temporary error" attempts=2124 err="engine stage failed: temp: temporarily cannot insert new safe block: failed to create new block via forkchoice: unrecognized rpc error: Invalid parameters"

**Comment by wbnns** [comment]
@germashevanton Hi there! It looks like you may have missed a network upgrade or the chain state has gotten corrupted. Can you please join the official [Base Discord](https://base.org/discord) and open a #developer-support ticket? We can take a closer look at your configuration and state there. 👍
