### ISSUE TITLE
transaction type not supported error in Go-Ethereum client

### ISSUE THREAD

**Issue by TangMonk** [base-org/node#230]
```
block, err := consts.Web3ClientHTTP.BlockByNumber(context.Background(), big.NewInt(oldBlockNum))
if err != nil {
  fmt.Println("Error fetching block", oldBlockNum, err)
  continue
}
```

<img width="648" alt="image" src="https://github.com/base-org/node/assets/3498786/474ac651-104b-48a9-89e7-782b7e852122">

I am using github.com/ethereum/go-ethereum v1.13.14

**Comment by roberto-bayardo** [comment]
You need to use [op-geth](https://github.com/ethereum-optimism/op-geth), not geth, which is extended to handle OP-stack system transactions.

**Comment by TangMonk** [comment]
> You need to use [op-geth](https://github.com/ethereum-optimism/op-geth)* , not geth, which is extended to handle OP-stack system transactions.

WOW, Thanks a lot!

Maybe the doc should be update

<img width="341" alt="image" src="https://github.com/base-org/node/assets/3498786/499f2ce1-91f7-4fb9-a76a-e62a9d3ff25c">

**Comment by wbnns** [comment]
@TangMonk We will add this to the docs, thanks 👍
