### ISSUE TITLE
Add more BOOTNODES in global worldwide area

### ISSUE THREAD

**Issue by TangMonk** [base-org/node#231]
All of the BOOTNODES are from USA, Not convenient for people from other areas, I am living in China, the syncing is so slow and often interrupt.

<img width="1252" alt="image" src="https://github.com/base-org/node/assets/3498786/f68d39c4-b6a7-4c30-99c2-6beb4fd5c9c2">

Could u plz add HK, Japan, or Singapore boot nodes?

**Comment by wbnns** [comment]
@TangMonk Heya, thanks; I renamed your other issue and we'll track this there: #222
