### ISSUE TITLE
Specify correct path for GETH_HOST_DATA_DIR

### ISSUE THREAD

**Issue by pyropy** [base-org/node#239]
Once when snapshot download is complete and extracted I'm left with directory named `snapshot` which contains `mainnet/download/geth/`. 

Does this `geth` folder actually represent correct value for `GETH_HOST_DATA_DIR` or should it actually point to `snapshot` directory?

**Comment by ifsayyes** [comment]
I took a snapshot using this command: 
# Move all the snapshot files from the directory snapshots/mainnet/download/geth/ to the working directory geth/.
cd /home/base_chain/geth-data && mv -f snapshots/mainnet/download/geth/* geth/

I can read the snapshot blocks, but when I run 'docker compose up --build -d', it has been running for over 6 hours and still hasn't started syncing! It's showing the following error:
Served eth_coinbase conn=194.67.206.46:33410 reqid=2 duration="76.346µs" err="etherbase must be explicitly specified"

I hope this helps with the issue you're facing with the snapshot directory.

![image](https://github.com/base-org/node/assets/135924607/ed019e55-9e4b-418e-8191-7fcf287aae04)

**Comment by wbnns** [comment]
@pyropy In case helpful, here are instructions you can follow that will help you: https://hackmd.io/@wbnns/restore-a-base-node-from-snapshot

If that doesn't work and you're still encountering a problem, please join the [Base Discord](https://base.org/discord) and open a ticket in the `#developer-support` channel. We can help you there. 👍
