### ISSUE TITLE
trying to install a node and am getting this error.

### ISSUE THREAD

**Issue by Gerincon** [base-org/node#248]
node-create-node-1  | t=2024-04-24T04:22:36+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE_L2_ENGINE_AUTH_RAW=688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a"
node-create-node-1  | t=2024-04-24T04:22:36+0000 lvl=warn msg="Found a deprecated flag which will be removed in a future version" flag_name=beta.extra-networks
node-create-node-1  | t=2024-04-24T04:22:36+0000 lvl=warn msg="The beta.extra-networks flag is deprecated and can be omitted safely."
node-create-node-1  | t=2024-04-24T04:22:36+0000 lvl=eror msg="Cannot configure network and rollup-config at the same time.\nStartup will proceed to use the network-parameter and ignore the rollup config.\nConflicting configuration is deprecated, and will stop the op-node from starting in the future.\n" network=base-sepolia rollup_config=sepolia/rollup.json
node-create-node-1  | t=2024-04-24T04:22:36+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node config: misconfigured L1 Beacon API endpoint: expected L1 Beacon API endpoint, but got none"
node-create-node-1 exited with code 1

**Comment by wbnns** [comment]
@Gerincon 

Hello, it looks like the `OP_NODE_L1_BEACON` value wasn't configured correctly on Line 11 of your ENV; please make sure that line is uncommented and that your endpoint is reachable.

If you're still having trouble after doing this, please join the [Base Discord](https://base.org/discord) and open a ticket in the #developer-support channel. We can help you there. 👍
