### ISSUE TITLE
failed to sync, keep attemting connection and looking for peers

### ISSUE THREAD

**Issue by NKCATCAT** [base-org/node#249]
![image](https://github.com/base-org/node/assets/133855452/c288785c-1faf-4d4f-9234-c3083bc44acf)
![image](https://github.com/base-org/node/assets/133855452/1e325db2-e963-4717-a00b-abd55a78beed)

**Comment by wbnns** [comment]
@NKCATCAT 

Thanks for your report. Please join the [Base Discord](https://base.org/discord) and open a ticket in the `#developer-support` channel. On Discord we can take a closer look at your specific configuration to see what the issue might be.
