### ISSUE TITLE
I'd like to ask about the issue with OP_NODE_L1_BEACON.

### ISSUE THREAD

**Issue by ismystyle** [base-org/node#255]
I installed according to https://docs.base.org/tutorials/run-a-base-node/, but I kept getting a prompt.

node_1  | t=2024-05-09T05:04:53+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE_L2_ENGINE_AUTH_RAW=688f5d737bad920bdfb2fc2f488d6b6209eebda1dae949a8de91398d932c517a"
node_1  | t=2024-05-09T05:04:53+0000 lvl=warn msg="Found a deprecated flag which will be removed in a future version" flag_name=beta.extra-networks
node_1  | t=2024-05-09T05:04:53+0000 lvl=warn msg="The beta.extra-networks flag is deprecated and can be omitted safely."
node_1  | t=2024-05-09T05:04:53+0000 lvl=error msg="Cannot configure network and rollup-config at the same time.\nStartup will proceed to use the network-parameter and ignore the rollup config.\nConflicting configuration is deprecated, and will stop the op-node from starting in the future.\n" network=base-mainnet rollup_config=mainnet/rollup.json
node_1  | t=2024-05-09T05:04:53+0000 lvl=info msg="Rollup Config" l2_chain_id=8453 l2_network=Base l1_chain_id=1 l1_network=mainnet l2_start_time=1686789347 l2_block_hash=0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd l2_block_number=0 l1_block_hash=0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771 l1_block_number=17481768 regolith_time="@ genesis" canyon_time="@ 1704992401 ~ Thu Jan 11 17:00:01 UTC 2024" delta_time="@ 1708560000 ~ Thu Feb 22 00:00:00 UTC 2024" ecotone_time="@ 1710374401 ~ Thu Mar 14 00:00:01 UTC 2024" fjord_time="(not configured)" interop_time="(not configured)"
node_1  | t=2024-05-09T05:04:53+0000 lvl=info msg="Initializing rollup node" version=v1.7.5-e87e5ef2-1714565109
geth_1  | INFO [05-09|05:04:57.998] Looking for peers                        peercount=1 tried=209 static=0
geth_1  | INFO [05-09|05:05:08.058] Looking for peers                        peercount=1 tried=58  static=0
node_1  | t=2024-05-09T05:05:09+0000 lvl=error msg="Error initializing the rollup node" err="failed to check L1 Beacon API version: operation failed permanently after 5 attempts: http Get failed: Get \"http://localhost:4000/eth/v1/node/version\": dial tcp 127.0.0.1:4000: connect: connection refused"
node_1  | t=2024-05-09T05:05:09+0000 lvl=error msg="error getting latest header" err="Post \"https://go.getblock.io/e5e9029ab51c4d848a3342baec0e32b6\": context canceled"
node_1  | t=2024-05-09T05:05:09+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node: failed to check L1 Beacon API version: operation failed permanently after 5 attempts: http Get failed: Get \"http://localhost:4000/eth/v1/node/version\": dial tcp 127.0.0.1:4000: connect: connection refused"

**Comment by ivesnikiema** [comment]
Hey try replacing localhost with you local ip address e.g `OP_NODE_L1_BEACON=http://192.168.x.xx:4000`

**Comment by wbnns** [comment]
@ismystyle 

Hello, it looks like the endpoint isn't valid for the Beacon provided as @ivesnikiema -- can you please update and let us know the results? Also that this port is reachable to your beacon node from the docker container?

Lastly, what are you running for the beacon node?

**Comment by wbnns** [comment]
@ismystyle 

Since it's been some time without a reply, going ahead and closing this issue for now. If you're still encounter a problem, just let me know and we can troubleshoot further.
