### ISSUE TITLE
Suggest right disk size requirement for base node

### ISSUE THREAD

**Issue by DSdatsme** [base-org/node#256]
Please help in recommending the right disk size for booting up a new base node from scratch.

1.  Disk size mentioned in the [repo](https://github.com/base-org/node?tab=readme-ov-file#hardware-requirements) which is 4TB and [docs](https://docs.base.org/tutorials/run-a-base-node/#hardware-requirements) i.e. 2.5TB is inconsistent

2.  Currently the snapshot size for mainnet is 3.4TB in zip. That means if someone wants to boot up a new base node, they would need at least 7TB of disk space, 3.5TB for zip download, and at least 3.5TB for extracting the data. 

This means to do this efficiently and make it future-proof, do we have to boot up a server with a 10TB disk? or am I doing something wrong?

**Comment by nooperpudd** [comment]
just very simple, downloading and extracting 
```export LATEST=$(curl https://base-snapshots-mainnet-archive.s3.amazonaws.com/latest) && wget https://base-snapshots-mainnet-archive.s3.amazonaws.com/${LATEST} -O - | tar -xzvf - -C /data/base```

**Comment by wbnns** [comment]
@DSdatsme 

Heya! Thanks for raising this point; opened a PR on both repositories to update this to be more explicit:
https://github.com/base-org/web/pull/515
https://github.com/base-org/node/pull/262
