### ISSUE TITLE
The opnode is not compatible with Erigon.

### ISSUE THREAD

**Issue by temuera** [base-org/node#261]
When fetching historical receipts, it cannot correctly parse the Receipt.blobGasPrice field.

Base Version: 0.8.3, with snapshot base-mainnet-archive-1714488087.tar.gz
Erigon Version: 2.60.0
Beacon: Erigon with Caplin archive.
Args: --l1.trustrpc=true --l1.rpckind=erigon 

```
INFO [05-22|03:35:47.936] Optimistically queueing unsafe L2 execution payload id=74f9f3..ec7ff0:14765400
WARN [05-22|03:35:49.590] Derivation process temporary error       attempts=20 err="temp: failed to fetch receipts of L1 block 0xc3baaff826162ee1efdf59aa43248a909a904fbf63a447eff721d3dc2c65dbce:19741521 (parent: 0x1206aa9016288d60bda8258c5254835d8ab558a31499af4755c328003d8a9c86:19741520) for L1 sysCfg update: 1 error occurred:\n\t* json: cannot unmarshal hex string without 0x prefix into Go struct field Receipt.blobGasPrice of type *hexutil.Big\n\n"

```

**Comment by mbndao** [comment]
I meet the same issue.

**Comment by wbnns** [comment]
@temuera 

Hi there! Have you made any configuration changes to `.env.mainnet`, `.env.sepolia`, `op-node-entrypoint` or `geth-entrypoint` other than providing the L1 and Beacon endpoints?

Ccc: @mbndao

**Comment by mbndao** [comment]
> @temuera
> 
> Hi there! Have you made any configuration changes to `.env.mainnet`, `.env.sepolia`, `op-node-entrypoint` or `geth-entrypoint` other than providing the L1 and Beacon endpoints?
> 
> Ccc: @mbndao

Yes there are some changes.
`op-node-entrypoint` :
```
-exec ./op-node
+exec ./op-node --l1.trustrpc --l1.rpckind=erigon
```
`.env.mainnet`: 
```
-OP_NODE_L1_ETH_RPC=https://1rpc.io/eth
+OP_NODE_L1_ETH_RPC=http://xx.xx.xx.xx:8545

 # [required] replace with your preferred L1 CL beacon endpoint:
-OP_NODE_L1_BEACON=https://your.mainnet.beacon.node/endpoint-here
+OP_NODE_L1_BEACON=https://docs-demo.quiknode.pro
```

which `http://xx.xx.xx.xx:8545` is my local eth Erigon node rpc url.

**Comment by temuera** [comment]
> @temuera
> 
> Hi there! Have you made any configuration changes to `.env.mainnet`, `.env.sepolia`, `op-node-entrypoint` or `geth-entrypoint` other than providing the L1 and Beacon endpoints?
> 
> Ccc: @mbndao

This may be due to the different encoding returned by GETH and ERIGON when communicating with L1.
GETH HEX Version: *big.Int geth/core/types/receipt.go L:67
Erigon DEX Version: uint256.Int erigon/eth/ethutils/receipt.go L:80

**Comment by kajeagentspi** [comment]
Fixed on erigon 2.60.1

**Comment by wbnns** [comment]
@kajeagentspi Ok, great, thanks for letting us know. 👍

@temuera @mbndao Can you all please upgrade and LMK if you're still encountering a problem?

**Comment by wbnns** [comment]
@temuera @mbndao If you all are still having a problem, PLMK and I will reopen this.
