### ISSUE TITLE
Op stack maybe can upgrade

### ISSUE THREAD

**Issue by iandareen** [base-org/node#266]
When fetching historical receipts, it cannot correctly parse the Receipt.blobGasPrice field.

Base Version: 0.8.3, with snapshot base-mainnet-archive-1714488087.tar.gz
Erigon Version: 2.60.0
Beacon: Erigon with Caplin archive.
Args: --l1.trustrpc=true --l1.rpckind=erigon

INFO [05-22|03:35:47.936] Optimistically queueing unsafe L2 execution payload id=74f9f3..ec7ff0:14765400
WARN [05-22|03:35:49.590] Derivation process temporary error       attempts=20 err="temp: failed to fetch receipts of L1 block 0xc3baaff826162ee1efdf59aa43248a909a904fbf63a447eff721d3dc2c65dbce:19741521 (parent: 0x1206aa9016288d60bda8258c5254835d8ab558a31499af4755c328003d8a9c86:19741520) for L1 sysCfg update: 1 error occurred:\n\t* json: cannot unmarshal hex string without 0x prefix into Go struct field Receipt.blobGasPrice of type *hexutil.Big\n\n"

**Comment by kajeagentspi** [comment]
Fixed on erigon 2.60.1

**Comment by wbnns** [comment]
Duplicate, related to #261
