### ISSUE TITLE
Add blob archiver options

### ISSUE THREAD

**Issue by rabbitprincess** [base-org/node#268]
add blob archiver flag for synchronizing nodes that are older than 18 days.
https://github.com/ethereum-optimism/optimism/issues/9992

op-node-entrypoint
```
ADDITIONAL_ARGS=""

if [ "${OP_NODE_L1_BLOB_ARCHIVER+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --l1.beacon-archiver=$OP_NODE_L1_BLOB_ARCHIVER"
fi

....

exec ./op-node \
   $ADDITIONAL_ARGS
```

**Comment by roberto-bayardo** [comment]
better to your .env.mainnet file:

`L1_BEACON_ARCHIVER=...`
