### ISSUE TITLE
add blob archiver flag for synchronizing nodes that are older than 18 days. ethereum-optimism/optimism#9992  op-node 

### ISSUE THREAD

**Issue by melai278** [base-org/node#270]
ADDITIONAL_ARGS=""

if [ "${OP_NODE_L1_BLOB_ARCHIVER+x}" = x ]; then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS --l1.beacon-archiver=$OP_NODE_L1_BLOB_ARCHIVER"
fi

....

exec ./op-node \
   $ADDITIONAL_ARGS

**Comment by roberto-bayardo** [comment]
would recommend specifying this in your .env.mainnet file to avoid modifying the entrypoint file.

**Comment by wbnns** [comment]
Closing, duplicate of #268
