### ISSUE TITLE
v0.9.0 release package looks wrong, can not run the base node

### ISSUE THREAD

**Issue by wangjiangw** [base-org/node#283]
in the v0.9.0, the release package looks different with v0.8.3 and can not build image correctly, for example, the Dockfile should be placed in node directory, not in node/geth, and it lacks the mainnet directory ？ the image run needs mainnet/genesis-l2.json

**Comment by danyalprout** [comment]
Hi @wangjiangw, thanks for reaching out. As part of v0.9.0 we changed the layout of the repository to allow us to support additional execution nodes.

For the image, you can either use our prebuilt one [here](https://github.com/base-org/node/pkgs/container/node), or you should be able to build it locally via docker:

```
cd node
docker build -t base-geth-node -f geth/Dockerfile .  
# note the context needs to be the root of the directory and the -f needs to specify the nested dockerfile
```

You should also be able to build it via `docker compose build`. Please let me know if you have any issues -- thanks!

**Comment by wangjiangw** [comment]
@danyalprout yes, i have rebuilt image, i think you should update the website or readme, haha. and another question, the env still contains mainnet/rollup config, but the release package not, is that ok for running the containers ? i have copy the mainnet directory manuly.
