### ISSUE TITLE
Snapshots for reth?

### ISSUE THREAD

**Issue by parsdextra** [base-org/node#290]
Hey all,

Having a really hard time getting geth to sync on v0.9.0, are there daily chain snapshots for reth anywhere?

**Comment by danyalprout** [comment]
Snapshots are [here](https://docs.base.org/tutorials/run-a-base-node/#snapshots) for Geth. Eventually we'll publish Reth snapshots too -- but not firm ETA.

**Comment by daothanginspius** [comment]
I cannot synchronize using current data, but can only synchronize when downloading the latest snapshot.
Not sure what is the cause of this problem? How can I still use the current data?

**Comment by danyalprout** [comment]
Is this for geth or for reth?

**Comment by danyalprout** [comment]
These are now live, see:
https://github.com/base-org/web/pull/651

I would advise, we still consider Reth for Base to be in beta.
