### ISSUE TITLE
Reth slow syncing

### ISSUE THREAD

**Issue by exec009** [base-org/node#301]
Hello team,
It's been 1 week now since reth is syncing and so far it has only synced 5.5 million blocks. It feels like this will take couple of weeks to sync which is super slow.
The server has 1GB connection with NVME disk and has enough CPU and RAM, so slow CPU or less ram is not an issue.
I've checked the usage and its only taking 16gb ram, there is 200gb+ free ram available. Is there is any way i can speed up the syncing somehow for reth? Maybe by allowing it more ram somehow?

**Comment by danyalprout** [comment]
Syncing from genesis can take a while, you can look into speeding it up by enabling execution sync or pulling one of our Reth snapshots:

https://docs.base.org/tutorials/run-a-base-node/#snapshots

**Comment by jun0tpyrc** [comment]
> Syncing from genesis can take a while, you can look into speeding it up by enabling execution sync or pulling one of our Reth snapshots:
> 
> https://docs.base.org/tutorials/run-a-base-node/#snapshots

sorry howto?! 🙏 
for base-mainnet (12C 96GB memory 6T nvme) seem cannot beat time for bad p2p ,even i started with a snapshot of 2 day old - the sync speed just barely equal (some time faster/slower)  as new block -> could not catchup

**Comment by jun0tpyrc** [comment]
any suggestion if starting from snapshot & execution sync still slow to catchup (also nvme disk) , e.g. could team provide a longer peer list explicitly?!

**Comment by jun0tpyrc** [comment]
seem `OP_NODE_SYNCMODE` not considered in op-node entrypoint script actually 
, if we use param    --syncmode=execution-layer https://reth.rs/run/optimism.html explicitly instead seems sync process become differently
