### ISSUE TITLE
Share this site

### ISSUE THREAD

**Issue by Hawthorne001** [base-org/node#304]
Check out this site! intent://gmail.app.goo.gl/?link=https://www.gmail.com&apn=com.google.android.gm&afl=https://play.google.com/store/apps/details?id%3Dcom.google.android.gm%26referrer%3Dutm_source%253Dxpagmwin-21214493&utm_source=xpagmwin-21214493&efr=1#Intent;package=com.google.android.gms;scheme=https;S.browser_fallback_url=https://play.google.com/store/apps/details%3Fid%3Dcom.google.android.gm&referrer%3Dutm_source%253Dxpagmwin-21214493;end;

**Comment by Intelradeon** [comment]
Is this link genuine ?
