### ISSUE TITLE
Is the source code for the node available?

### ISSUE THREAD

**Issue by Mattiatore** [base-org/node#312]
Is the source code for the node available? I am asking because I could only find docker files and references that a base node is built on top of the optimism stack (but not exactly the same I guess). For example I was trying to find where the config parameter `OP_NODE_L2_ENGINE_AUTH` is used but I couldn't find any that are code related

**Comment by roberto-bayardo** [comment]
It's the exact same software as the optimism stack.   Cheers.

**Comment by roberto-bayardo** [comment]
see: https://github.com/ethereum-optimism/optimism/blob/5c8ebef990ca327470858ae245c6d0869ef2458c/op-node/flags/flags.go#L64
