### ISSUE TITLE
Monitoring of nodes. --ethstats

### ISSUE THREAD

**Issue by herculessx** [base-org/node#33]
With an `--ethstats` tag to be added to the docker-compose.yml file, running nodes can be monitored. It can also be integrated with an .env file to monitor the version of the node.  a good way to monitor the nodes.

https://github.com/goerli/ethstats-server

docker-compose.yml
example

```
"--ethstats=NODE-NAME:base@base",

```
.env file

```
BASECLIENT_IMAGE=base/base-client:0.0.3
```

![image](https://user-images.githubusercontent.com/101635385/226113768-574cd3e0-41d6-400c-ad15-7b4a45e8e40c.png)

**Comment by ameya-deshmukh** [comment]
@wbnns is this available to work on? Would love to contribute if possible. :)

**Comment by asapika** [comment]
yes

**Comment by wbnns** [comment]
@ameya-deshmukh 

Heya! Thanks for offering!

I'd yield to @mdehoog or another core contributor to weigh in with feedback.

**Comment by roberto-bayardo** [comment]
> @wbnns is this available to work on? Would love to contribute if possible. :)

I'm not sure this option should be on by default, but if it were in the config in a way that was easy to enable, that might be helpful.

**Comment by obia5313** [comment]
Z26uzaew80509012930Z

**Comment by successfull2014** [comment]
от successfull2014, абузы

**Comment by t23e3** [comment]
от t23e3 абузы

**Comment by somuas43** [comment]
Пересылка с somuas35, абузы

**Comment by successfull2015** [comment]
от successfull2015, абузы

**Comment by catherineblansh** [comment]
от Кейт абузы

**Comment by sv3tlana01k** [comment]
абузы от Светланы01к
