### ISSUE TITLE
Node stops syncing out of nowhere, then resumes

### ISSUE THREAD

**Issue by heitorPB** [base-org/node#51]
Our Base node is misbehaving in a way that puzzles me. 

Out of nowhere, it stops syncing. After some time of inactivity, it resumes syncing. Then it stops. Then it syncs... this makes our node unable to catch up with the chain and it is ~20k blocks behind.

There are no errors in the logs.

The server is more powerful than the requirements, we have more than 1TB available storage, over 50 GB of available RAM, gigabit network.

What I see in the logs are many "blocks" like this:

```
INFO [05-10|18:48:08.750] Starting work on payload                 id=0x648946b36a090f1a
INFO [05-10|18:48:08.752] Imported new potential chain segment     number=4,248,797 hash=1016b4..1c4486 blocks=1 txs=1  mgas=0.000 elapsed="719.261µs" mgasps=0.000    age=14h47m58s dirty=0.00B
INFO [05-10|18:48:08.753] Chain head was updated                   number=4,248,797 hash=1016b4..1c4486 root=399f45..ec29bc elapsed="59.931µs"  age=14h47m58s
```

And then nothing for several minutes. The `geth` process goes to sleep for some reason. After taking a nap for about an hour, we see this in the logs:

```
INFO [05-10|19:35:28.773] Writing clean trie cache to disk         path=/data/geth/triecache threads=1
INFO [05-10|19:35:28.773] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-10|19:35:29.203] Persisted the clean trie cache           path=/data/geth/triecache elapsed=430.639ms
```

And then nothing happens in the logs... this process repeats over and over and our node never gets all the blocks.

Is this a known behavior? How do we fix it?

**Comment by roberto-bayardo** [comment]
Haven't heard other reports of this. My much-more-poorly provisioned server keeps up fine without stalls.  Is this a VPS or a physical machine?

**Comment by wbnns** [comment]
@heitorPB 

Heya! Just wanted to follow-up to see if you're still experiencing this issue? Is your node currently running? If so, could you please let me know its current block height?

**Comment by heitorPB** [comment]
Hi, @wbnns!

We are still experiencing the issues. Our node is on block 4_798_325.

Is there anything I can do to troubleshoot this issue further?

**Comment by wbnns** [comment]
@heitorPB 

> Hi, @wbnns!
> 
> We are still experiencing the issues. Our node is on block 4_798_325.
> 
> Is there anything I can do to troubleshoot this issue further?

Thanks for following up! Strange! Alongside @roberto-bayardo, I also haven't heard of any other reports of this. 

Is it possible your connecting might be getting throttled?

**Comment by wbnns** [comment]
@heitorPB

Hello, since it's been a couple of weeks and we haven't heard back, closing this PR for now. If it's still a problem just let us know and we can reopen. Where we left off is that we were curious if it is possible that your connection might be getting throttled which could be causing the syncing issue.

We haven't seen this issue reported elsewhere so that's the main area we would be curious to troubleshoot with you next. 👍

**Comment by heitorPB** [comment]
The issue was gone after the latest release. I updated our node and it finally started catching up without interruptions. It is now in sync with the network.

**Comment by wbnns** [comment]
@heitorPB 

Ok, great! Thanks for following up to let us know! Glad it is all sorted. 👍
