### ISSUE TITLE
Can't deploy ERC-1820, non-EIP-155 protected txs rejected even with --rpc.allow-unprotected-txs set

### ISSUE THREAD

**Issue by d10r** [base-org/node#53]
I'm trying to deploy [ERC-1820](https://eips.ethereum.org/EIPS/eip-1820) for the [Superfluid protocol](https://github.com/superfluid-finance/protocol-monorepo). That requires a non-EIP-155 tx ("Nick's method").
I synced a testnet node and expected this to work after starting it with the flag `--rpc.allow-unprotected-txs=true`. However it still fails, with the node printing this log message:
```
geth_1  | WARN [05-31|11:56:48.983] Served eth_sendRawTransaction            conn=172.26.0.1:41282 reqid=15               duration=155.265946ms err="only replay-protected (EIP-155) transactions allowed over RPC"
```
Please advise me how to allow non-EIP-155 txs on my local node.
Alternatively, please deploy ERC-1820. Other protocols may eventually need it too.

**Comment by roberto-bayardo** [comment]
Unfortunately there's no way to enable eip-155 transactions but can you use the deterministic deployment proxy instead? https://github.com/Arachnid/deterministic-deployment-proxy

This is deployed on Base goerli.

**Comment by roberto-bayardo** [comment]
Hmm looking more deeply I don't think you'd get the same address if you were to use the deterministic deployment proxy.  Let me look into deploying ERC-1820 ourselves.

cc: @mdehoog

**Comment by philipandersson** [comment]
@roberto-bayardo Appreciate that! Please let us know as soon as you can deploy this. Right now this is blocker for us deploying our protocol onto BASE.

**Comment by roberto-bayardo** [comment]
Here ya go! https://goerli.basescan.org/tx/0xfefb2da535e927b85fe68eb81cb2e4a5827c905f78381a01ef2322aa9b0aee8e 

Please confirm this suits your needs. We'll be enabling pre-155 txs more broadly so in the future you should be able to submit these on your own with the appropriate node/rpc support.

**Comment by philipandersson** [comment]
@roberto-bayardo Thanks a lot, should be working from what I can tell.
