### ISSUE TITLE
Detail questions on running base node

### ISSUE THREAD

**Issue by TonyS001** [base-org/node#64]
I run a base node under the instruction in README and now I have some detail questions.
1. How can I stop the node? I notice there are two processes running: geth and op-node. Is there any simple command to safely stop all processes or I have to kill them one after one by myself?
2. How can I start the node again? Run `docker compose up` every time?
3. Are there log files for geth and op-node and how can I config them, like output dir?
4. How to set metrics and connect to Grafana? 

Looking forward to your reply. Thanks!

**Comment by mdehoog** [comment]
1. If you are using docker compose to run, it is safe to simply kill this process, it will kill the individual containers safely.
2. Yes, running `docker compose up` will start the node again.
3. The logs are currently output to stdout by default. You can also view them by running `docker logs <container-name>`. For more detail about docker compose logging, see https://docs.docker.com/compose/compose-file/compose-file-v3/#logging
4. To view metrics, you'll need to run a prometheus deployment that points at the metrics ports (i.e. `7300`), and a grafana on top of that to visualize the data.

**Comment by TonyS001** [comment]
Thanks for reply! I have some other questions.
I want to run an archive node and I start the node without changing any other parameters. Does the node synchronize both block data and state data by default? I want the node has the ability to query both history block and history state. How much disk space do I need to prepare to support such an archive node?

**Comment by mdehoog** [comment]
Yes, the node synchronizes both block and state data. Currently geth disk usage from an archive node is around 350gb for Goerli, and around 5gb for Mainnet. This will grow as the chain is used.
