### ISSUE TITLE
Node configuration problem 

### ISSUE THREAD

**Issue by herculessx** [base-org/node#70]
The ( select your network here ) sections in the docker-compose.yml file will break the configuration because there is a # sign at the beginning

https://github.com/base-org/node/blob/main/docker-compose.yml#L13
https://github.com/base-org/node/blob/main/docker-compose.yml#L28

I think it would be good to prepare a separate repo for those who want to install mainnet

```  env_file:
      # select your network here:
#      - .env.goerli
#      - .env.mainnet

**Comment by aflock** [comment]
Thanks for raising @herculessx. We may make a separate repo in the future but prefer to keep this single one now for ease of maintenance and discoverability. The need to uncomment these lines in the config is listed in the readme.
