### ISSUE TITLE
Node version reporting as 0.1.0 although running 0.3.0

### ISSUE THREAD

**Issue by PeaStew** [base-org/node#75]
It appears the version string was not updated for the latest releases when querying:

`{
	"jsonrpc":"2.0",
	"method":"web3_clientVersion",
	"params":[
	],
	"id":1
}`

returns:
`"result": "Geth/v0.1.0-unstable-a84992a3-20230427/linux-amd64/go1.19.9"`

docker shows:

`ghcr.io/base-org/node:v0.3.0`

Even https://goerli.base.org/ returns the wrong version

Needs to be fixed because it's not easy to track version changes for updates without this being correct

**Comment by aflock** [comment]
Hey @PeaStew, this is a geth API and will return the version of Geth currently running
https://github.com/ethereum/go-ethereum/blob/2274a03e339f213361453590b54917bbfd0a0c31/node/api.go#L329
It's not intended to track the release version of this node software. 
The best way to track released versions would be to subscribe to this projects [releases](https://github.com/base-org/node/releases)
Is that what you're trying to do?

**Comment by PeaStew** [comment]
> Hey @PeaStew, this is a geth API and will return the version of Geth currently running https://github.com/ethereum/go-ethereum/blob/2274a03e339f213361453590b54917bbfd0a0c31/node/api.go#L329 It's not intended to track the release version of this node software. The best way to track released versions would be to subscribe to this projects [releases](https://github.com/base-org/node/releases) Is that what you're trying to do?

We are trying to track our version of the software running on our load balancer vs the version that has been released, so that we get alerting on new versions. This is pretty normal to need to do.

**Comment by aflock** [comment]
Makes sense a something you need to do. This API won't be the correct way to implement that however - possibly you could use some docker tooling to monitor the version of software you are running?

**Comment by PeaStew** [comment]
Sure, why make it easy

**Comment by mdehoog** [comment]
Hey @PeaStew, thanks for raising the issue! The current version comes from these constants: https://github.com/ethereum-optimism/op-geth/blob/optimism/params/version.go#L32-L37

I agree it would be preferable for `web3_clientVersion` to return the correct version information. I'm working with the Optimism team to figure out a way to keep this in sync with the released tag.

**Comment by mdehoog** [comment]
this is now fixed:
```
> curl -d '{ "jsonrpc":"2.0", "method":"web3_clientVersion", "params":[ ], "id":1 }' -H "Content-Type: application/json" https://goerli.base.org
{"jsonrpc":"2.0","result":"Geth/v1.101200.1-rc.2-36831023-20230823/linux-amd64/go1.19.12","id":1}
```
