### ISSUE TITLE
Node cannot start: `Derivation process temporary error`

### ISSUE THREAD

**Issue by sljeff** [base-org/node#76]
The node is not starting and there are repeated errors occurring.

```
node-node-1  | t=2023-07-26T09:18:09+0000 lvl=warn msg="Derivation process temporary error"     attempts=13 err="temp: failed to fetch receipts of L1 block 0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771:17481768 for L1 sysCfg update: receipt 2 has unexpected tx index 0"
```

**Comment by sljeff** [comment]
I'm using a paid blockpi node

It seems that the error `0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771` is not a legal eth tx hash

**Comment by aflock** [comment]
That is the hash for the genesis block: https://etherscan.io/block/17481768
I wonder if the blockpi node is a full node and not an archive node? If it is a full node (with only the last 128 blocks) it will not have the history required to fetch this block.

**Comment by mdehoog** [comment]
What does this return?
```
curl -d '{"id":0,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xe080e65b2f599279599ba4c59b96bad843ec29a50490ab15cab330b9c945e1c4"]}' -H "Content-Type: application/json" <BLOCKPI_RPC_URL>
```

It should return a JSON blob containing `"transactionIndex":"0x2"` within. If anything else, it seems like possibly your L1 node is malfunctioning.

**Comment by sljeff** [comment]
@aflock 

Yes, this is an archive node.

@mdehoog 

Yes, it returned content does contain `"transactionIndex":"0x2"` as you said.

I'm sorry, but I haven't tried starting a node myself anymore as the node provider I use, blockpi, already offers direct access to the base chain.

**Comment by mdehoog** [comment]
I have reproduced this on a blockpi node. It looks like sometimes their `eth_getTransactionReceipt` returns an empty response. For example: `{"jsonrpc":"2.0","id":26,"method":"eth_getTransactionReceipt","params":["0x2094a0de142cfebbcbdfc38d5c2410e6cdba0e81dad1e27e874fb69901484995"]}` normally works fine, but occasionally returns `{"jsonrpc":"2.0","id":26,"result":null}`.

You can reproduce this with the following script. This will panic on the public-facing blockpi node, but succeed using another node. Would recommend using another provider for your L1 node.

```golang
package main

import (
	"context"
	"github.com/ethereum-optimism/optimism/op-node/client"
	"github.com/ethereum-optimism/optimism/op-node/sources"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/rpc"
	"math/big"
	"time"
)

func main() {
	ctx := context.Background()
	c, err := rpc.DialContext(ctx, "https://ethereum.blockpi.network/v1/rpc/public")
	if err != nil {
		panic(err)
	}
	r := client.NewBaseRPCClient(c)
	e := ethclient.NewClient(c)
	block, err := e.BlockByNumber(ctx, big.NewInt(17481768))
	if err != nil {
		panic(err)
	}
	testCfg := &sources.EthClientConfig{
		// receipts and transactions are cached per block
		ReceiptsCacheSize:     1000,
		TransactionsCacheSize: 1000,
		HeadersCacheSize:      1000,
		PayloadsCacheSize:     1000,
		MaxRequestsPerBatch:   20,
		MaxConcurrentRequests: 10,
		TrustRPC:              true,
		MustBePostMerge:       false,
		RPCProviderKind:       sources.RPCKindBasic,
		MethodResetDuration:   time.Minute,
	}
	ec, err := sources.NewEthClient(r, log.Root(), nil, testCfg)
	if err != nil {
		panic(err)
	}
	_, _, err = ec.FetchReceipts(ctx, block.Hash())
	if err != nil {
		panic(err)
	}
}
```
