### ISSUE TITLE
Txpool Question

### ISSUE THREAD

**Issue by kugimiya530** [base-org/node#78]
Hi did Base Chain support Txpool (pending pool)

for my friend he can access pending pool by public node

but can't access pending pool by private node

did he bs me or something...

**Comment by mdehoog** [comment]
No, currently the Base mempool is private. You can read about this here: https://community.optimism.io/docs/developers/bedrock/differences/#mempool

This may change in the future as the sequencer is decentralized.

**Comment by kugimiya530** [comment]
> No, currently the Base mempool is private. You can read about this here: https://community.optimism.io/docs/developers/bedrock/differences/#mempool
> 
> This may change in the future as the sequencer is decentralized.

Thx alot

**Comment by top2hightech** [comment]
Is base mempool still private?
