### ISSUE TITLE
wallet keep issue transaction would cause overdraft 

### ISSUE THREAD

**Issue by kugimiya530** [base-org/node#83]
please check below address

he can't do anything operation  transfer  swap  ....etc

always show  "transaction would cause overdraft"

0x6EA30AEC700158DF6aFA5888D83aa48f86AadbdF

------------
but he deposit more eth to solve this problem and solve for a while

after few transction now issue again

did Base chain will often issue this problem?

lol stuck 21eth ... he keep deposit to try , and  now stuck 28eth

-----------------
after deposit to 28eth finally this problem solve, how can we avoid this problem

**Comment by mdehoog** [comment]
On Base, the gas required to include transactions in blocks is denominated in ETH. If your wallet doesn't contain enough ETH to cover transaction gas, these transactions will fail. Transferring more ETH to your wallet, as you are doing, is the correct approach.
