### ISSUE TITLE
Geth-entrypoint custom settings ignored 

### ISSUE THREAD

**Issue by Ethwookie** [base-org/node#88]
Custom settings in Geth-entrypoint are ignored. The file appears to be overwritten (confirmed by entering into container shell and reading Geth-entrypoint file).

**Comment by danyalprout** [comment]
Hi @Ethwookie 👋 

Thanks for reporting. Just to make sure I understand, are you modifying the [geth-entrypoint](https://github.com/base-org/node/blob/main/geth-entrypoint) file to add an additional setting?

AFAICT changes you make to `geth-entrypoint` shouldn't be overriden, as the file is [copied directly into the container](https://github.com/base-org/node/blob/main/Dockerfile#L37). Can you try running it with `docker compose up --force-recreate --build` to check the container is up to date after you've change the file.

Thanks

**Comment by stephanegrosheitsch** [comment]
Hello, 
Hello
Hello, What can I do ?
root@vmi1239249:~/node# docker compose up
validating /root/node/docker-compose.yml: services.geth.env_file must be a string
root@vmi1239249:~/node# ls
CONTRIBUTING.md  docker-compose.yml  Dockerfile  geth-entrypoint  goerli  LICENSE  logo.webp  mainnet  op-node-entrypoint  README.md  SECURITY.md
root@vmi1239249:~/node# nano README.md
root@vmi1239249:~/node# docker compose up --force-recreate --build
validating /root/node/docker-compose.yml: services.geth.env_file must be a string
root@vmi1239249:~/node#

**Comment by danyalprout** [comment]
@stephanegrosheitsch you'll need to choose your settings files [here](https://github.com/base-org/node/blob/main/docker-compose.yml#L14-L16) and [here](https://github.com/base-org/node/blob/main/docker-compose.yml#L29-L31).

You can find more instructions in the readme [here](https://github.com/base-org/node/blob/main/README.md#usage).
