### ISSUE TITLE
start syncing from recent block

### ISSUE THREAD

**Issue by iht76** [base-org/node#90]
If I don't need full history, is there a way to start syncing from most recent block?

If I have fully synced node, how can I back it up, so I can start syncing from there on a new server?

**Comment by wbnns** [comment]
@iht76 

> If I don't need full history, is there a way to start syncing from most recent block?

Yeah, that would be super-convenient but a full sync is needed.

> If I have fully synced node, how can I back it up, so I can start syncing from there on a new server?

For a new server, you can download the latest snapshot, which is updated every hour, like so:

Open your `docker-compose.yml` file and add this under the `geth` tag
```
cd node
nano docker-compose.yml
```
```
volumes:
      - $HOME/node/data:/data
```
 --- >>  ctrl x+ y  save

![image](https://github.com/base-org/node/assets/1130872/3a461dec-65fd-4004-8c6e-148da54cfe1c)

2️⃣  node folder directory and create a folder named data
```
docker compose down
mkdir data
```
3️⃣  For testnet or mainnet, run the following codes inside the data folder and wait for it to load
```
cd data
```
Testnet
`wget -O - https://base-goerli-archive-snapshots.s3.us-east-1.amazonaws.com/$(curl https://base-goerli-archive-snapshots.s3.us-east-1.amazonaws.com/latest) | tar -zxf-`

Mainnet
`wget -O - https://base-mainnet-archive-snapshots.s3.us-east-1.amazonaws.com/$(curl https://base-mainnet-archive-snapshots.s3.us-east-1.amazonaws.com/latest) | tar -zxf-`

4️⃣  After the installation is finished, go back to the node folder and run your node.
```
cd ~/node
docker compose up -d
docker compose logs -f --tail "100"
```
Hope that helps!
