### ISSUE TITLE
Response size should not greater than 2097152 bytes

### ISSUE THREAD

**Issue by phongdatgl** [base-org/node#98]
Hello, I try run Base node in Docker. I got an error when sync blocks.
`warn msg="Derivation process temporary error"     attempts=348 err="temp: failed to fetch receipts of L1 block 0x57bd24685fba47da5f038e691c7c4ef2fd965c1dcc1b82cb95e1b66f5cdb9e86:17481818 for L1 sysCfg update: 20 errors occurred:\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\t* response size should not greater than 2097152 bytes\n\n"`

Anyone can help me ?
Thank you very much !

**Comment by wbnns** [comment]
@phongdatgl 

Heya, what are you using for your L1 RPC?

**Comment by wbnns** [comment]
@phongdatgl

Since we haven't heard back from you for some time I'm going to go ahead and close this issue.

If you're still having a problem please let us know and we can reopen. 👍 🤝
